---
title: 'STAT 687 Homework #0'
date: ''
fontsize: 11in
output:
  pdf_document:
    fig_cap: yes
    includes:
      in_header: ../css/jkf.header.tex
  html_document:
    css: ../css/homework.css
    fig_cap: yes
    highlight: pygments
    theme: readable
    toc: yes
geometry: margin=1in
citation_package: natbib
---

Welcome to STAT 687 - Math of Reliability! This 

1. Install the R software package (3.2.0 or later) to the computers you intend to work on.

> - For AFIT computers, see network folder R:/Stats/R. Double-click the install link for the latest version available and follow the prompts for a standard installation.

> - For home computers, install directly from <http://www.r-project.org/>.  Click on the CRAN link on the left side and install the latest version available.

2. Install the RStudio IDE

> - For AFIT computers, see network folder R:/Stats/R. Double-click the "RStudio.exe" file for the latest version available and follow the prompts for a standard installation.

> - For home computers, install directly from <http://www.rstudio.com/products/rstudio/download/>.  Click on the installer link at the bottom of the page for the appropriate operating system.

3. Install the RSPLIDA package, the R version of the software package put out by Meeker & Escobar.  

> - On the Blackboard page for this course, access the "R & RSplida" folder and download the RSplidaAlpha.zip file to your computer.  Make sure to note the location where this file was saved.

4. Read Appendix B and Chapter 1 in Meeker & Escobar.  We'll cover these pretty quickly the first week.  

