---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 13.`r ex = ex+1; ex`

 Show that (\ref{equation:paris.diffyq.solution})  is the solution to (\ref{equation:paris.diffyq}). 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Use the degradation equation (\ref{equation:paris.diffyq.solution})  to obtain an expression for the time that $\degpath(t)$ crosses a specified $\critdeg$. 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Show that (\ref{equation:luvalle.meeker.diffyq.sol})  is the solution to (\ref{equation:luvalle.meeker.diffyq}). 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Use  the degradation equation (\ref{equation:luvalle.meeker.diffyq.sol2})  to obtain an expression for the time that $\A_{2}(t)$ crosses a specified $\A_{2f}$. 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Determine the value of $N$ needed in Algorithm~\ref{algorithm:mc.evaluation.of.f.of.t} to evaluate $F(t)$ at the point where $F(t)=.01$ so that the probability that Monte Carlo error in evaluation is less than .0001, with probability approximately .95.  Use the normal distribution approximation to the binomial probability. 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Discuss the advantages and disadvantages of using Algorithm~\ref{algorithm:evaluation.of.f.of.t.by.int}  versus \ref{algorithm:mc.evaluation.of.f.of.t} when estimating $F(t)$ from degradation data. 


# From the Text Exercise 13.`r ex = ex+1; ex`

 Consider the analysis of the laser degradation data in Example~\ref{example:simple.deg.laser}. 
 

a. \label{exerpart:5per} Repeat the analysis using the time at which current has increased by 5\% to define failure. 

a. \label{exerpart:15per} Repeat the analysis using the time at which current has increased by 15\% to define failure. 

a. Compare the results in parts  \ref{exerpart:5per} and \ref{exerpart:15per}. Comment on the differences in assumptions needed to estimate these two different distributions.  


# From the Text Exercise 13.`r ex = ex+1; ex`

 \label{exercise:block.error.rate.degradation.data} Appendix Table~\ref{atable:block.error.rate.degradation.data} gives degradation data on block error rates (the ratio of number of bytes with errors to the total number of bytes tested) of magneto-optic data storage disks tested for 2000 hours at 80$^{\circ}C$ and 85\% relative humidity. Use the simple analysis method described in Section~\ref{section:app.deg.anal} to estimate the failure-time distribution of these disks at 80$^{\circ}C$ and 85\% relative humidity where failure is defined as the time that it takes to reach an error rate of $50 \times 10^{-5}$ (a safe level at which error correcting codes can be expected to correct errors). 


# From the Text Exercise 13.`r ex = ex+1; ex`

 \label{exercise:asym.deg} As an electronic device ages, its power output decreases.  Because the degradation results from a simple one-step chemical reaction with a limited amount of harmful material available for reaction, the decrease in power can be described by the degradation model $\degpath(t) = \beta_{2}[1 -  \exp(-\beta_{1} t )]$ where $\degpath(t)$ is the power output at time $t$, $\beta_{2} < 0 $ is nearly the same for all units, and $\beta_{1}$, comes from a lognormal distribution.  System performance degrades noticeably when $\degpath(t)$ falls below $\critdeg$. Thus we define a failure as the point in time when $\degpath(t) < \critdeg$. 
 

a. Describe some possible physical reasons for the asymptotic behavior of $\degpath(t)$. 

a. What happens, in the long run, if $\beta_{2} > \critdeg $? 

a. Assuming that $\critdeg$ is a fixed constant and that $\beta_{2} < \critdeg $, derive an expression for $F(t)$, the failure time cdf.  


# From the Text Exercise 13.`r ex = ex+1; ex`

 Suppose the actual degradation path of a particular unit is given by $\degpath(t) = \beta_{1} t$ where $-\log(\beta_{1})$ varies from unit to unit according to a $SEV(\mu, \sigma)$ distribution. If failure occurs when $\degpath(t) > \critdeg$, where $\critdeg$ is a fixed constant, show that the failure time distribution is Weibull. 


