---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 20.`r ex = ex+1; ex`

 Consider the ALT described in Exercise~\ref{exercise:devicec.analysis}.  The reliability engineers who ran that accelerated test want to run another accelerated test on a similar device. They have asked you to help them evaluate the properties of some alternative test plans. 
 

a. Relative to the plan used in Exercise~\ref{exercise:devicec.analysis}, what modifications would you suggest for evaluation? 

a. List the criteria that you would use to compare the plans and make a recommendation on how to conduct the accelerated test.  


# From the Text Exercise 20.`r ex = ex+1; ex`

 In general, planning values are needed to do test planning and to determine the sample size needed to provide a specified degree of precision. 
 

a. Explain why such planning values are needed. 

a. Product or reliability engineers may be able to provide some useful information, but they cannot be expected to provide accurate planning values (otherwise they would have no reason to run the test!). What can be done to protect against the use of potentially misspecified planning values?  


# From the Text Exercise 20.`r ex = ex+1; ex`

 In planning an ALT, the large-sample approximate variance of the ML estimator of a particular quantile of the failure-time distribution at use conditions is often used to judge the precision that one could expect from a proposed test plan. Suppose that the Arrhenius/lognormal model will provide an adequate description of the relationship between life and temperature. As described in Appendix Section~\ref{asection:asymptotic.covariance}, there are computer algorithms that can be used to compute the large-sample approximate  covariance matrix $\vcvmat_{\thetavechat}$ of the ML estimates $\hat{\beta}_{0}$, $\hat{\beta}_{1}$, and $\hat{\sigma}$. In this case, $\vcvmat_{\thetavechat}$ will be a function of the proposed test plan and the parameters $\beta_{0}$, $\beta_{1}$, and $\sigma$. 
 

a. Given the individual elements of $\vcvmat_{\thetavechat}$, provide an expression for the large-sample approximate variance of the ML estimator of the $p$ quantile at use temperature $\Temp_{U}$. Do not use matrix algebra. 

a. Approximate standard errors of ML estimators from a proposed test plan can also be obtained by using Monte Carlo simulation. Explain the advantages and disadvantages of this approach relative to using the large-sample approximate variance.  


# From the Text Exercise 20.`r ex = ex+1; ex`

 An ALT is going to be conducted to investigate the effect of size on the life of an insulating material. The accelerating variable will be voltage. Based on previous experience, for purposes of planning the experiment, use the model \begin{displaymath} \Pr[\rv \leq t;\Thick,\Vpm] = \Phi_{\sev}  \left[\frac{\log(t)-\mu(\Thick,\Vpm)}{\sigma} \right] \end{displaymath} where  $\mu = \beta_{0}+ \beta_{1} \Thick + \beta_{2} \Vpm$, $\Thick$ is the specimen size in cm , $\Vpm$ is voltage stress in volts per mm, and $\sigma$ is constant. 
 

a. What would be the model relating $\mu$ to the $\Thick$ and voltage (instead of volts per mm)? 

a. What is an important advantage of modeling and experimenting in terms of $\Vpm$ and $\Thick$ rather than voltage and $\Thick$?  


# From the Text Exercise 20.`r ex = ex+1; ex`

 Consider the planning values given in Example~\ref{example:alt.planning.values}. 
 

a. Compute the proportion failing after 6 months at 80$\degreesc$. 

a. Suppose that there is a simple chemical degradation process that causes the adhesive to degrade over time. Compute the implied activation energy for this degradation process assuming that the Weibull shape parameter is $\beta=1/\sigma$=2, and 3.  


