---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 11.`r ex = ex+1; ex`

 Wilk, Gnanadesikan, and Huyett~(1962b) give the number of weeks until failure for a sample of 34 transistors subjected to accelerated conditions. The reported times, with  the number of ties shown in parentheses, were 3, 4, 5, $ 6 (2) $, 7, $8 (2) $, $9 (3)$, $ 10 (2) $, $ 11 (3) $, $ 13 (5) $, $ 17 (2)$, $19 (2) $, 25, 29, 33, $42 (2)$, 52.  The other 3 transistors had not failed at the end of 52 weeks. \begin{itemize} 

a. Use ML to estimate the parameters of the BISA, IGAU, gamma, and lognormal distributions to these data using a discrete-data likelihood. Plot all of these estimates on lognormal probability paper and compare the different estimates.  Describe any important differences that you see in the estimates. 

a. Redo the gamma distribution analyses assuming that the failures occurred at exactly the reported time.  Are the differences of practical importance in this example? \end{itemize} 


# From the Text Exercise 11.`r ex = ex+1; ex`

 \label{exercise:lfp.sen.anal} The engineers who collected the IC data from Example~\ref{example:lfp.trunc} felt that if the life test had been extended for another 50,000 hours (corresponding to the technological life of the application system), only another 2 or 3 failures might have been observed.  Use this information to construct several Weibull and lognormal probability plots for the failure-time distribution for the defective subpopulation. 


# From the Text Exercise 11.`r ex = ex+1; ex`

 \label{exercise:lfp.reparameterization} For the Weibull LFP (limited failure population) model with cdf given in (\ref{equation:lfp.cdf}), a proportion $p$ of the units in the  population is defective and will eventually fail (according to a Weibull distribution) and all other units are immune to failure. 
 

a. What is the practical interpretation of the parameter $\mu$ in this model? 

a. Generally in a life test of a limited failure population, if the test is stopped far before all of the units in the population have failed, the parameters $\mu$ and $p$ will be highly correlated. Give an intuitive explanation for this. 

a. The expected proportion of units failing in a life test of length $t_{c}$ might be a more "stable" parameter to estimate. Explain why. Write down the reparameterized model, and describe the steps that you would use to find the ML estimates of this new parameter as well as $\mu$ and $\sigma$.  


# From the Text Exercise 11.`r ex = ex+1; ex`

 \label{exercise:lfp.factor.likelihood} Refer to Exercise~\ref{exercise:lfp.reparameterization}.  Show that the likelihood for the LFP model with a single censoring time can be factored into two components, one a binomial with parameter $\pi=p \times \Phi\{[\log(t_{c})-\mu]/\sigma\}$ and another consisting of a right-truncated failure time distribution with truncation time $\tau_{i}^{U}=t_{c}$. 


# From the Text Exercise 11.`r ex = ex+1; ex`

 \label{exercise:trun.dist} Suppose that $T$ has a $WEIB(\mu, \sigma)$ distribution. Show that 
 

a. \label{exer.part:left.truncated.cdf} The cdf of the left-truncated Weibull distribution is  
$$
 F(t;\tau^{L}; \mu,\sigma)= 1-\exp \left [ (\tau^{L}/\eta)^{\beta}-(t/\eta)^{\beta} \right ], \quad t>\tau^{L} \ge 0 
$$ where $\eta=\exp(u)$ and $\beta=1/\sigma$. 

a. \label{exer.part:right.truncated.cdf} The cdf of the right-truncated Weibull distribution is  
$$
 F(t; \tau^{U}; \mu,\sigma)= \frac{ 1-\exp \left [-(t/\eta)^{\beta} \right ]     }     { 1-\exp \left [-(\tau^{U}/\eta)^{\beta} \right ]     },\quad 0< t \le \tau^{U}. 
$$ 

a. \label{exer.part:left.right.truncated.cdf} The cdf of the left-truncated and right-truncated Weibull distribution is 
$$
 F(t; \tau^{L},\tau^{U}; \mu,\sigma)= \frac{  \exp \left [-(\tau^{L}/\eta)^{\beta} \right ] -\exp \left [-(t/\eta)^{\beta} \right ]     }     {  \exp \left [-(\tau^{L}/\eta)^{\beta} \right ] -\exp \left [-(\tau^{U}/\eta)^{\beta} \right ]     },\quad \tau^{L}< t \le \tau^{U}. 
$$  


# From the Text Exercise 11.`r ex = ex+1; ex`

 Refer to Exercise~\ref{exercise:trun.dist}, part~\ref{exer.part:left.truncated.cdf}.  What is the cdf of the truncated distribution when $\sigma=1$? 


# From the Text Exercise 11.`r ex = ex+1; ex`

 \label{exercise:vendor1.trun} Consider the data in Examples~\ref{example:electronic.subsystem.data}, \ref{example:pretest.and.left.trun}, and \ref{example:pretest.mle}. Truncate the Vendor 1 data at 1000 hours and compare the resulting fit with that for Vendor 2. Can you detect any difference that might be considered to be important? 


# From the Text Exercise 11.`r ex = ex+1; ex`

 Consider the results from either Exercise~\ref{exercise:trunc.releff.avar} or from Exercise~\ref{exercise:trun.cens.sim}. Provide an intuitive explanation for the reason that precision from the censored distribution is much better than from the truncated distribution. 


# From the Text Exercise 11.`r ex = ex+1; ex`

 During a single month a company sold 2341 modems.  These modems have a 36-month warranty. During the first 24 months, 75 of these modems had been returned for warranty service.  Suppose that it is reasonable to assume that this is the number failing out of the 2341 modems that were sold.  From previous experience with similar products, it is known that a Weibull distribution with a shape parameter of $\beta=.85$ provides an adequate description of the failure time distribution. 
 

a. Show that the conditional probability of failing in the third year of life, given survival up to two years, can be expressed as a truncated distribution. 

a. \label{exer.part:modem.warranty1} Although the times to failure for the returned modems were not available, it is still possible to compute an estimate of the Weibull cdf using the given value of $\beta=.85$.  Show how to do this. 

a. Use the estimate from part~\ref{exer.part:modem.warranty1} to compute an estimate for the number of units that will fail in the third year of operation. 

a. Suppose that you had learned that two years after being sold, between 5\% and 10\% of the purchased modems had never been put into service. How would you do part\ref{exer.part:modem.warranty1}?  


