---
output: html_document
---

__Discuss the assumptions that would be needed to convert the heat exchanger data from calendar time in Figure 1.6 to operating-time data in Figure 1.7 and then use these data for purposes of analysis and inference on the life distribution of heat exchanger tubes of the type in these heat exchangers.__

`r teachingSMRD:::solution()$begin`
The phrase "...analysis and inference on the life distribution..." implies a common life distribution is desired to make statements on the lifetime of the overall population of heat exchanger tubes based on the combined data obtained at each of the three plants. 

Assumptions:

- Though the tubes were probably manufactured at different times, we would have to assume that the tubes installed in the three plants were produced using manufacturing processes that could be considered approximately the same.

- No external events (e.g., earthquake, maintenance actions) that could cause failures occurred at a particular plant during the observation period.

- All three plants were run under similar environmental conditions and similar workloads for the entire period of observation.
`r teachingSMRD:::solution()$end`

