---
output: html_document
---

__It is an unfortunate fact of test-planning life that "best" test plan for a particular situation, according to specified criteria, will usually depend on the unknown parameters (or "you have to know the answer to plan the test"). Material in Chapter 10 suggests getting around this by using planning values based on engineering information or past experience with past products. Suggest a practical strategy for protecting against misspecification of these planning values when planning a life test (i.e., choosing the number of units to test and the length of the test).__

`r teachingSMRD:::solution()$begin`
If the true model parameters were known, there would be no reason to run the life test.  The text suggests a helpful strategy using planning values to serve as initial estimates of the model parameters.  These planning values are often obtained by consulting engineers, statisticians, and other test experts who have familiarity with the system to be tested.  However, even if "planning values" for conducting a life test are elicited from individuals familiar with the failure process, they cannot (and should not ) be expected to be correct.  A reasonable strategy to protect against errors in specifying these planning values is to:

1. Start test-planning using the "best guess" planning values
2. Perform a sensitivity analysis on how small changes to the planning values effect the end result (i.e. the number of required specimens)
3. Extend the sensitivity analysis to incorporate larger changes to the planning values
4. Based on the results of steps (3) and (4) determine the possible planning parameter  values that would result in a test that is either cost or time prohibitive.
5. Consult with subject matter experts to determine whether planning parameter values could exceed the critical values.
6. Map out a region in the parameters space and do the needed test-planning evaluations over a set of points spanning that region.
`r teachingSMRD:::solution()$end`
