---
output: html_document
---

__For the Weibull LFP (limited failure population) model with cdf given in (\ref{equation:lfp.cdf}), a proportion $p$ of the units in the  population is defective and will eventually fail (according to a Weibull distribution) and all other units are immune to failure.__

a. __What is the practical interpretation of the parameter $\mu$ in this model?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Generally in a life test of a limited failure population, if the test is stopped far before all of the units in the population have failed, the parameters $\mu$ and $p$ will be highly correlated. Give an intuitive explanation for this.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __The expected proportion of units failing in a life test of length $t_{c}$ might be a more "stable" parameter to estimate. Explain why. Write down the reparameterized model, and describe the steps that you would use to find the ML estimates of this new parameter as well as $\mu$ and $\sigma$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
