---
output: html_document
---

__The Monte Carlo approach to making Bayesian inferences is convenient, intuitive, and easy to explain.__

a. __Show that the expected number of retained units using the Monte Carlo technique is given by__
$$
E(M^{*}) = M \int f(\theta)R(\theta)d\theta
$$
__Hint: the number of retained units has a binomial distribution with parameters $M$ and success probability equal to $Pr[U \le R(\theta)]$, where $U$ and $R(\theta)$ are independent.  Then the proof consists of showing that $Pr[U \le R(\theta]=\int f(\theta) R(\theta) d\theta$ which is teh expected relative likelihood under the prior.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Use the result in part (a) to argue that if there is agreement between the prior pdf and the likelihood then the ratio $M^{*}/M$ and the prior pdf and posterior pdf are similar.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Discuss the case in which the prior pdf and the likelihood do not agree and indicate when the prior and the posterior pdfs tend to agree (or disagree) in this case.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
