---
output: html_document
---

__Revisit the shock absorber data introduced in Example 3.8 and given in Appendix Table C.2.  There were actually two different causes of failure for this product.  The analyses in Chapters 3 and 8 ignored the different "failure modes" in the analysis.  An alternative analysis (important for some purposes) would take into consideration the different failure modes.  Such an analysis is straightforward when the failure times for the two different modes are statistically independent.__

a. __Assuming that the failure modes are independent, fit Weibull distributions separately to estimate the time to failure for each mode.  Also fit other parametric distributions to the individual failure modes to see if there are other distributions fit better than the Weibull.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

b. __Suppose that the shock absorber is a series system that fails as soon as there is a failure due to one mode or the other.  Combine the results from part (a) to obtain an estimate of the cdf for the shock absorbers with both modes acting together.  Plot these on Weibull probability paper and compare the results with the analyses that ignores the differences between the two different failure modes.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

c. __Provide an intuitive explanation for the result in part (b)__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

d. __Explain why the agreement between the two methods of analysis is so good in this case (as compared to Example 15.6). In general, when would you expect to see more important differences between the analysis that accounts for the different failure modes and the analysis that does not account for the different failure modes?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
