---
output: html_document
---

__Consider an NHPP model with a strictly positive recurrence rate $\nu(t)$, [i.e.,$\nu(t)>0$ for all $t$ in $[0,\infty)$].  Let $\rv_{1},\rv_{1},\dots$ be the random times at which the recurrent events occur in the stochastic process.  Let $W_{1}=\mu(\rv_{1}),W_{2}=\mu(\rv_{2}) $ denote transformed times, where $\mu(t)$ is the process MCF.__

a. __Show that the time transformation $w=\mu(t)$ is monotone increasing. This implies that  the inverse transformation $t=\mu^{-1}(w)$ is well defined.__ 

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Let $N_{W}(a)$ be the number of events in the interval $[0,a)$ in the $W$ time scale. Show that events in nonoverlapping intervals are independent and that__
$$
\begin{aligned}
 N_{W}(0)&=0\\\\
 \Pr\left[N_{W}(a,b) = 
   d\right]&=\Pr\{N\left[\mu^{-1}(a),\mu^{-1}(b) \right] = d\}\\\\
 &=\frac{(b-a)^{d}}{d!}\exp[-(b-a)],\,d=0,1,2, \dots.
\end{aligned}
$$
__This implies that in the $W$ time scale, the point process is HPP with a constant recurrence rate equal to 1.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Using the result in part (b), show that the interrecurrence transformed times $W_{i}-W_{i-1}=\mu(\rv_{i-1}, \rv_{i})$, $i=1,2, \dots$, (where  $W_{0}=0$) are $\rm iid$ with an $\EXP(1)$ distribution.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

