---
output: html_document
---

__In some reliability applications it is common to use transformations of explanatory variables in regression modeling (models involving such transformations are described in Chapter 18). Also, it might be possible to find a distribution other than the Weibull that will provide a better fit to the data.  Use the glass capacitor data in Examples 17.11 and 17.12, and fit the following alternative models.__

a. __In the two variable regression model, use the transformations $x_{1}=1/(\mbox{temp}^{\circ}C+ 273.15)$ (known as the Arrhenius relationship) and $x_{2}=\log(\mbox{Voltage})$ (known as the inverse power relationship).  Compare estimates of $t_{.5}$ at the different levels of temperature and voltage used in the life test. Is there evidence that these factors affect life? Explain.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Repeat the analysis in part (a), using the normal distribution instead of the Weibull distribution. Again, compare estimates of $t_{.5}$ at the different levels of temperature and voltage used in the life test.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
