---
output: html_document
---

__Refer to Exercise 8.7.__

a. __Assume that the activation energy of the observed failure mode is $E_{a}=1.2\;eV$ and that the Arrhenius relationship provides an adequate description of the effect of temperature on the reaction rate. Compute estimates of the lognormal distribution parameters at $50^{\circ}C$, $80^{\circ}C$, and $120^{\circ}C$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __On lognormal probability paper, plot the estimate of the life distributions at $50^{\circ}C$, $80^{\circ}C$, and $120^{\circ}C$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Repeat part (a), using an activation energy of $E_{a}=.7\;eV$ and also plot these results.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain the effect that an incorrect assumption about  activation energy could have on estimates of life at low temperature.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

