---
output: html_document
---

__Example 19.6 showed how to use an omnibus likelihood ratio test to compare fitting individual lognormal distributions at each level of temperature and fitting the Arrhenius-lognormal ALT model.  This provides an overall test for model adequacy.__

a. __Explain, precisely, the hypothesis or hypotheses being tested in Example 19.6.__ 

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain which constrained and unconstrained models you would fit in order to test the assumption of a common $\sigma$ at all levels of temperature. Do not assume anything about the temperature-life relationship.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain possible likelihood ratio tests on whether $\sigma$ is constant, under the assumption that $\mu$ is linearly related to $11605/\mathtt{temp}\;K$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain how to do a likelihood ratio test to check the assumption that $\mu$ is linearly related to $11605/\mathtt{temp}\;K$ versus an alternative relationship with curvature, assuming that $\sigma$ does not depend on temperature.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
