---
output: html_document
---

__The ALT data on the mylar-polyurethane insulating structure in Appendix Table C.13 are complete data (no censored observations). Thus it is possible to fit a lognormal distribution to these data using the standard least-squares regression analysis procedure in a standard statistical package. Use these data, dropping the $361.4 kV/mm$ observations, to do the following.__

a. __Use such a statistical package to compute the least squares estimates for the inverse power relationship lognormal model.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Plot the regression estimates of median of the failure-time distribution on log-log axes. Also plot the sample median at each level of voltage. What conclusions can you draw from this?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compare the least squares estimates with estimates obtained by using ML estimation with the inverse power relationship lognormal model. What differences do you notice in the parameter estimates?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
