---
output: html_document
---

__Write down an expression for the likelihood of the V7 tube data in Table 1.4. Also give an explicit expression for the constant term $\mathcal{C}$.__

`r teachingSMRD:::solution()$begin`
The V7 is included in the `SMRD` package under the name `v7tube`.  The data (shown in the table below) are lifetimes for 188 vacuum tubes used in high-power transmitter.

```{r}
knitr::kable(SMRD::v7tube, 
             caption = 'The V7 tube dataset from Table 1.4 in the SMRD text')
```

We see that there were no 'exact' observations as failures were found to have occurred during routine inspections conducted every 25 days up to 100 days at which point the test was concluded.  Recall from Section 2.4.3 that each observation contributes the overall likelihood by an amount equal to the cdf at the upper endpoint of the inspection interval minus the cdf at the lower endpoint of the inspection interval.  As the observations occurred over 5 intervals, the total likelihood is expressed as

$$
\begin{aligned}
\mathscr{L}(\theta|DATA)= \mathcal{C}\;&[F(\;\;25|\theta)-F(\;\;\;\;0|\theta)]^{109}&\times\\ &[F(\;\;50|\theta)-F(\;\;25|\theta)]^{42}&\times \\
&[F(\;\;75|\theta)-F(\;\;50|\theta)]^{17}&\times \\
&[F(100|\theta)-F(\;\;75|\theta)]^{7}&\times \\
&[F(\;\;\infty|\theta)-F(100|\theta)]^{13}
\end{aligned}
$$

Of course, we don't know the underlying distribution that governs the lifetimes of these vacuum tubes.  However, by substituting the cdf of various distributions into the above expression we can find $\theta$ such that the total likelihood is maximized.   The distribution with the highest total likelihood is then considered to be the 'most likely'.

The value of the $\mathcal{C}$ term is expressed as 

$$
\mathcal{C}=\frac{n!}{d_1!\cdot d_2! \cdot d_3! \cdot d_4! \cdot d_5!}
$$

where $n$ is the total number of samples and $d_1, \ldots, d_5$ are the number of observations in each of the 5 intervals.  This term is used because there are many ways that 109 specimens out of 188 total specimen could have failed in the first interval $(0, 25]$ days.  For the V7 tube data we compute $\mathcal{C}$ as

$$
\begin{aligned}
\mathcal{C}=&\frac{188!}{109!\cdot 42! \cdot 17! \cdot 7! \cdot 13!}\\\\
=&\frac{`r prod(188:110)`}{`r factorial(42)*factorial(17)*factorial(7)*factorial(13)`}\\\\
=&`r prod(188:110)/(factorial(42)*factorial(17)*factorial(7)*factorial(13))`.
\end{aligned}
$$

This means that there are $`r prod(188:110)/(factorial(42)*factorial(17)*factorial(7)*factorial(13))`$ possible ways to arrange 188 vacuum tube lifetimes into five intervals in the same arrangement as occurred in the `v7tube` data.  Note, we typically don't care about the value of $\mathcal{C}$ as it has no impact on the value of $\theta$ that maximizes the likelihood function.  
`r teachingSMRD:::solution()$end`
