---
output: html_document
---

__Appendix Table C.3 gives ADT data on the increase in resistance over time of carbon-film resistors tested at three different levels of temperature.  Suppose that failure is defined as the time at which the resistance has increased by $5\%$. Use the approximate method of analysis described in Sections 13.9 and 21.7 to analyze these data. In particular,__

a. __Make a plot the degradation versus time for each of the sample paths.  Use both log and linear axes.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Choose an appropriate transformation scale for the data to make the paths approximately linear. Fit a separate linear regression model to the appropriate subset of the data in each sample path. Plot the estimated regression estimates in various ways.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain the interpretation of the parameters of the regression model for the individual paths. In what sense are these regression parameters random?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute the average of the slope estimates within each temperature group.  Plot these averages versus $11605/(\mathtt{temp}\; ^oC + 273.15)$ (or, equivalently, plot on Arrhenius scales, as described in Exercise 18.11). Assess the adequacy of a linear relationship. What measure could you use, in an informal way, to help in this assessment?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Write down the temperature/degradation model implied by the relationship graphed in part (d). Obtain a graphical estimate of the activation energy for this degradation process.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute pseudo failure time for each of the sample paths and use these to do a life data analysis and to estimate the failure-time distribution at $50\;^oC$.__  

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
