---
output: html_document
---

__Refer to the sliding metal wear data in Appendix Table C.19, also used in Example 21.6. Data were collected by testing four specimens at three different levels of applied weight (10, 50, and 100 grams). Scar depth was measured at 2, 5, 10, 20, 50, 100, 200, and 500 cycles. Comment on the practical value and the potential cost of the additional information that would be obtained by__

a. __Sampling wear at $2,5,10,15,20,25, \dots, 495$, and $500$ cycles.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Sampling wear at $2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000$, and $5000$ cycles.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Testing eight units each at $10, 50$, and $100$ grams, using the original sampling rate in time.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Testing three units each at $10, 30, 60$, and $100$ grams, using the original sampling rate in time.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Testing three units each at $5, 20, 40$, and $50$ grams, using the original sampling rate in time.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Testing  three units each at $20, 60, 200$, and $400$ grams, using the original sampling rate in time.__ 

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
