---
output: html_document
---

__Some computer programs (e.g., statistical packages and spreadsheets) can be used to generate pseudorandom samples from a uniform distribution.  Let $U_{1},\ldots,U_{n}$ denote such a sample. Then $T_{1}=-\log(1-U_{1}),\ldots,T_{n}=-\log(1-U_{n})$ is a pseudorandom sample from an exponential distribution (to be described in more detail in Chapter 4).  Simulate a sequence of $50$ such samples each of size $n=200.$ For each sample:__

a. __Compute and plot $\hat{F}.$__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Make a histogram of the $50$ values of $\hat{F}(1).$__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Make a histogram of the $50$ values of $Z_{\hat{F}(1)}.$__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Make a histogram of the $50$ values of $Z_{logit(\hat{F})}.$__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compare the histograms in parts (c) and (d). Which statistic seems to be better approximated by a $NOR(0,1)$ distribution?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
