---
output: html_document
---

__Explain why the nonparametric estimate of $F(t)$ is a set of points for the heat exchanger data in Example 3.6 but a step-function for the shock absorber data in Example 3.9__

`r teachingSMRD:::solution()$begin`
The difference in these examples is what is known when a failure occurs.  In the heat exchanger problem, failures are only known to occur during the inspections at the end of the year.  If a heat exchanger pipe failed prior to the inspection, the exact failure time would be unknown.  It would be incorrect to plot the CDF as a step function between the inspections, since zero, one or many failures may have occured during the year, we just don't know when.

The battery data set lists exact failure times, so if no failures were observed between times $t_{1}$ and $t_{2}$, we know that no units failed between these two times and it is reasonable to assume that the value of nonparametric estimate of the cdf is constant between these times.
`r teachingSMRD:::solution()$end`
