---
output: html_document
---

__Consider the Plant 1 heat exchanger data in Figure 3.1__

a. __Write the likelihood for these data in terms of $\pi_{1},\pi_{2},\pi_{3},$ _and_ $\pi_{4}$__

`r teachingSMRD:::solution()$begin`
Recall that the $i^{th}$ inspection occurs at the end of interval $i$, $(t_{i}-t_{i-1})$.  The probability that an event of interest occurs during interval $i$ is expressed as $\pi_{i} = F(t_{i})-F(t_{i-1})$, where $F(\cdot)$ denotes the cdf of the underlying failure time distribution.  For the Plant 1 heat exchanger data, failures can occur in one of four intervals $[0,1),[1,2),[2,3),$ and $[3,\infty)$. The likelihood function for this data would then be expressed as shown below, where $\mathcal{C}$ is a constant that does not depend on $\mathbf{\theta}$.

$$
\mathcal{L}(\theta|t)=\mathcal{C}[F(1|\theta)-F(0|\theta)]^1[F(2|\theta)-F(1|\theta)]^2[F(3|\theta)-F(2|\theta)]^2[F(\infty|\theta)-F(3|\theta)]^{95}.
$$

The $\pi$ values are equivalent to each of the terms shown in the likelihood expression above (i.e. $\pi_{1} = F(t_{1}|\theta)-F(t_{0}|\theta)=F(1|\theta)-F(0|\theta)$).  Thus, the likelihood function for the Plant 1 heat exchanger data -- expressed in terms of $\boldsymbol{\pi}=(\pi_{1},\pi_{2},\pi_{3},\pi_{4})$ -- is shown below, where $\mathcal{C}$ is once again a constant that does not depend on $\mathbf{\pi}$.

$$
\mathcal{L}(\boldsymbol{\pi})=\mathcal{C}[\pi_{1}]^1[\pi_{2}]^2[\pi_{3}]^2[\pi_{4}]^{95}
$$
`r teachingSMRD:::solution()$end`

b. __Write the likelihood for these data in terms of $p_{1},p_{2},p_{3},$ _and_ $p_{4}$__

`r teachingSMRD:::solution()$begin`
Recall, that $p_{_{i}}=\pi_{i}/S(t_{i-1})$ is the conditional probability that a unit will fail in interval $i$, given that it had not failed in the previous intervals.  For the first interval $i = 1$, we know that the likelihood function, expressed in terms of the cdf $F(\cdot)$, is $F(t_{1})-F(t_{0}) = F(t_{1})$.  Observing, the expression for $p_{1}$ we see that 

$$
p_{_{i = 1}}=\frac{\pi_{1}}{S(t_{0})} = \frac{F(t_{1})-F(t_{0})}{1} = F(t_1).
$$

Thus the first term in the likelihood function is equal to $p_{1}$.  For the second interval $i=2$, the contribution to the likelihood function is expressed as $F(t_{2})-F(t_{1})$.  Relating this expression to $p_{2}$ we see that 

$$
p_{_{i = 2}}=\frac{\pi_{2}}{S(t_{1})} = \frac{F(t_{2})-F(t_{1})}{1-F(t_{1})}\\ 
$$

thus, $F(t_{2})-F(t_{1}) = p_{_{2}}(1-p_{_{1}})$, since $p_{_{1}} = F(t_{1})$.  Extending this to the final two intervals, results in the likelihood expression shown below (written in terms of $\mathbf{p}=(p_{1},p_{2},p_{3},p_{4})$)

$$
\mathcal{L}(\mathbf{p})=\mathcal{C}[p_{1}]^1[p_{2}(1-p_{1})]^2[p_{3}(1-p_{1})(1-p_{2})]^2[(1-p_{1})(1-p_{2})(1-p_{3})]^{95}.
$$

Note that $p_{4}=1$ in this case and has been omitted from the expression.
`r teachingSMRD:::solution()$end`
