---
output: html_document
---

__If the times to failure in a population are adequately described by a distribution with a decreasing hazard function, one might think that the surviving units in the population are getting better with time.  In fact, decreasing hazard functions are common for certain solid-state electronic components and electronic systems.  Weaker units fail early, after which the hazard decreases. For a mixture of two exponential distributions with $\gamma=0$ but different values of  $\theta$ (say $\theta_{1}=1$ and $\theta_{2}=5$), and equal proportions from the two populations, do the following:__

a. __Obtain an expression for the cdf of the mixture.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Obtain an expression for the pdf of the mixture.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Use the previous 2 parts to derive an expression for the hazard function  of the mixture.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Graph the mixture hazard from $t=0$ to $t=10$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __What is the shape of the mixture hazard? What is the intuition for this result?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __In what sense is the mixed exponential population "improving" with time (as suggested by the decreasing hazard function)?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
