---
output: html_document
---

__Starting with an ordinary piece of graph paper with linear divisions, perform the following steps to create Weibull probability paper with time ranging between $10$ and $1000$ and probability ranging between $.001$ and $.999.$ Refer to Figure 6.4 for an example. Alternatively, program a spread-sheet or statistical  package to do the same thing with computer graphics.__

a. __Find values of $\log[-\log(1-p)]$ for $p=.001$ and $p=.999.$ Use these to develop a linear axis on the right-hand side of the graph.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __For selected values of $p$ between .001 and .999 (e.g., .001, .01, .1, .3, .5, .7, .9, .99, .999) compute $\log[-\log(1-p)].$ Find this value on the right-hand side axis to determine the location of the $p$ label on the left-hand side axis.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Find values of $\log(t)$ for $t=10$ and $t=1000.$ Use these to develop a linear axis for $\log(t)$ on the top of the page.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __For selected values of $t$ between 10 and 1000 (e.g., 10, 20, 50, 100, 200, 500, 1000), compute $\log(t)$ and use the location on the top axis to determine the corresponding locations for the time labels on the bottom axis.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
