---
output: html_document
---

__Let $t_{1}, \ldots, t_{r}$ be the failure times in a singly time-censored sample of size $n$ from an $EXP(\theta)$ distribution. Suppose that the prespecified censoring time is $t_{c}$. The total time on test is $TTT=\sum_{i=1}^{r}t_{i}+(n-r)t_{c}$.__

a. __Write an expression for the log likelihood using the density approximation for the observations reported as exact failures.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Show that the ML estimate is $\hat{\theta}=TTT/r$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Use the result of part (a) to show that the ML estimate of $\theta$ is equal to $\infty$ (or "does not exist") when all the observations are censored.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Derive an expression for the relative likelihood similar to the one given in part (b) of Problem 7.1 (note that in this case $TTT/r$ plays the role of $\bar{t}$ and $r$ the role of $n$).__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
