---
output: html_document
---

__A large electronic system contains thousands of copies of a particular component, which we will refer to as Component-A (each system is custom-made to order and the actual number of components varies with the size of the particular system). The failure rate for Component-A is small, but because there are so many of the components in operation, failures are reported from time to time. A field tracking study was conducted to estimate the failure rate of a new design for Component-A (which was intended to provide better reliability at lower cost), to see if there was any real improvement. A number of systems were put into service simultaneously and monitored for 1000 hours. The total number of copies of Component-A in all of the systems was 9432. Failures of Component-A were observed at 345, 556, 712, and 976 hours. Failure mode analysis suggested that the failures were due to random shocks rather than any kind of quality defects or wearout. This, along with past experience with simpler components, suggested that an exponential distribution might be an appropriate model for the lifetime of Component-A.__

a. __Compute the ML estimate for the exponential mean $\theta$ for Component-A.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute an approximate $95\%$ confidence interval for $\theta$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain the interpretation of the confidence interval obtained in part (b).__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Explain the interpretation of the hazard function $\lambda=1/\theta$. In what way can this quantity be used to compute failure rates for Component-A or for the overall system?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Use the results of part (b) to obtain an approximate $95\%$ confidence interval for $\lambda$. Express this in units of FITs (failures per $10^{9}$ hours of operation).__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __The hazard for the old part was $\lambda_{\mbox{old}}=8.5 \times 10^{-7}$ (or 850 FITs). How strong is the evidence that reliability has improved with the new design? Describe how you would phrase a statement about the relative improvement.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute and plot the exponential $\hat{F}(t)$ from 0 to 10,000 hours on Weibull paper. Comment on the usefulness of this plot.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
