---
output: html_document
---

__Nelson (1982, page 105) provides data on minutes to breakdown for an insulating fluid. There were 11 tests at 30 kV.  After 100 minutes, there were $7$ breakdowns (failures) at the following times (in minutes): 7.74, 17.05, 20.46, 21.02, 22.66, 43.40, 47.30. The other $4$ units had not failed.__

a. __Make a Weibull probability plot and an exponential probability plot for these data.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __What do you think about the suggestion of using  an exponential distribution, $EXP(\theta)$, to model the data?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Assuming an exponential distribution, obtain the ML estimate of  $\theta$ and give an estimate of $se_{\hat{\theta}}$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute an approximate $95\%$ confidence interval for $\theta$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute the ML estimate of $t_{.1}$, the $.1$ quantile of the time to breakdown distribution.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute an approximate $95\%$ confidence interval for $t_{.1}$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

