---
output: html_document
---

__Use the diesel locomotive fan failure data in Appendix Table C.1 to do the following:__

a. __Fit an exponential distribution to the fan data.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Fit a Weibull distribution to the fan data.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Do a likelihood ratio test that the Weibull shape parameter is equal to 1. How would the conclusion affect fan replacement policy?__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute an approximate $95\%$ confidence interval for $t_{.1}$, the time at which $10\%$ of the fan population will fail, based on $Z_{that_{.1}} \overset{\cdot}{\sim} NOR(0,1)$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`

a. __Compute an approximate $95\%$ confidence interval for $t_{.1}$, based on $Z_{\log(that_{.1})} \overset{\cdot}{\sim} NOR(0,1)$.__

`r teachingSMRD:::solution()$begin`
`r teachingSMRD:::solution()$end`
