---
title: 'STAT 687 - Homework # 3'
author: "Due 23 November 2016"
fontsize: 11in
output:
  pdf_document:
    fig_cap: yes
    includes:
      in_header: ../scripts/tex/jkf.header.tex
  html_document:
    css: ../scripts/css/homework.css
    fig_cap: yes
    highlight: pygments
    theme: readable
    toc: yes
geometry: margin=1in
citation_package: natbib
---

```{r,echo=FALSE,message=FALSE, warning=FALSE}
source('../scripts/R/setup.R')
output <- getYAML('stat687-hw3.Rmd')$output
library(SMRD)
library(survival)
library(actuar)
library(evd)
```

## From the text problem # 6.5

Consider the ball bearing fatigue data given in Example 1.1 and Table 1.1

(a) Compute a nonparametric estimate of $F(t)$, the proportion of units failing as a function of time.  Plot your estimate on paper with linear scales

(b) Make a lognormal probability plot of the data.  This is accomplished by ordering the failure times in increasing order, $T_{(1)}\le...\le T_{(23)}.$  Then plot $t_{(i)}$ versus $(i-.5)/n$ on lognormal probability paper.

(c) Do the same as in part (b) but on Weibull probability paper.

(d) Comment on the adequacy of the lognormal and Weibull models to describe these data.

`r if(output=='pdf') '\\newpage'`

## From the text problem # 6.7

A sample of $100$ specimens of a titanium alloy were subjected to a fatigue test to determine the time to crack initiation.  The test was run up to a limit of $100,000$ cycles.  The observed time of crack initiation (in units of $1,000's$ of cycles) were: $18,32,39,53,59,68,77,78,93.$ No crack had initiated in any of the other $91$ specimens.

(a) Compute a nonparametric estimate, $\hat{F}(t)$ of the cdf $F(t)$ using both the simple binomial method and the Kaplan-Meier method (in this case the two methods provide the same answer)

(b) Plot $\hat{F}(t)$ on linear axes.

(c) Use $\hat{F}(t)$ to compute plotting positions and plot the data on Weibull paper.  Use the plot to obtain an estimate of the Weibull shape parameter $\beta$

(d) Comment on the adequacy of the Weibull distribution

(e) Comment on the adequacy of the available data if the purpose of the experiment was to estimate $t_{.1}.$

`r if(output=='pdf') '\\newpage'`

## From the text problem # 6.9

Using the life test data on silicon photodiode detectors from Exercise 3.12, construct probability plots for the exponential, Weibull, and lognormal distributions.  Which distributions look like they might provide an adequate model for photodiode detector life?

`r if(output=='pdf') '\\newpage'`

## From the text problem # 8.5

Return to the fatigue crack-initiation test in Exercise 6.7.  Fit a Weibull distribution with a given shape parameter $\beta=2.$

(a) Compute the ML estimate of $\eta.$  What is the practical interpretation of this estimate?

(b) Obtain the estimate $\hat{se}_{\hat{\eta}}.$

(c) Compute a conservative 95% confidence interval for $\eta.$

(d) Plot the Weibull estimate of $F(t)$ along with the nonparametric estimate.  Comment on the adequacy of the Weibull distribution to describe the data.

(e) What is an estimate of the .1 quantile of the time-to-initiation distribution?

(f) Compute a conservative 95% confidence interval for the .1 quantile of the time-to-initiation distribution.
