---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 5.`r ex = ex+1; ex`

 \label{exercise:simple.mix.exp} If the times to failure in a population are adequately described by a distribution with a decreasing hazard function, one might think that the surviving units in the population are getting better with time.  In fact, decreasing hazard functions are common for certain solid-state electronic components and electronic systems.  Weaker units fail early, after which the hazard decreases. For a mixture of two exponential distributions with $\gamma=0$ but different values of  $\theta$ (say $\theta_{1}=1$ and $\theta_{2}=5$), and equal proportions from the two populations, do the following: 
 

a. Obtain an expression for the cdf of the mixture. 

a. Obtain an expression for the pdf of the mixture. 

a. Use the previous 2 parts to derive an expression for the hazard function  of the mixture. 

a. Graph the mixture hazard from $t=0$  to $t=10$.  

a. What is the shape of the mixture hazard? What is the intuition for this result? 

a. In what sense is the mixed exponential population "improving" with time (as suggested by the decreasing hazard function)?  


# From the Text Exercise 5.`r ex = ex+1; ex`

 In some applications a sample of failure times comes from a mixture of subpopulations. 
 

a. Write down the expression for the cdf $F(t)$ for a mixture of two exponential distributions with means $\theta_{1}=1$ and $\theta_{2}=10$ (subpopulations $1$ and $2,$ respectively) with $\xi$ being the proportion from subpopulation 1. 

a. For $\xi=0, .1, .5, .9$ and $1,$ compute the mixture $F(t)$ for a number of values of $t$ ranging between $0$ and $30.$ Plot these distributions on one graph. 

a. Plot  $\log(t)$ versus $\log\{-\log[1-F(t)]\}$  for each $F(t)$ computed in part (b). Comment on the shapes of the mixtures of exponential distributions, relative to a pure exponential distribution or a Weibull distribution. 

a. Plot the hazard function $h(t)$ of the mixture distributions in part (b). 

a. Qualitatively, what do the Weibull plots in part (c) suggest about the hazard function of a mixture of two exponential distributions?  


# From the Text Exercise 5.`r ex = ex+1; ex`

 Show that the exponential distribution is a special case of the gamma distribution given in Section~\ref{section:gamma.distribution}. 


# From the Text Exercise 5.`r ex = ex+1; ex`

 Let $T_{(1)}$ denote the minimum of $m$ independent Weibull random variables with parameters $\mu_{i}, i=1, \ldots, m$ and constant $\sigma$.  Show that $T_{(1)}$ has a Weibull distribution. 


