---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 10.`r ex = ex+1; ex`

 Use the input information in Example~\ref{example:insulation.plan.info} to compute the planning values $\muplan$ and $\sigmaplan$ for both the lognormal and the Weibull distributions. Plot these cdfs on appropriate probability paper.  Also, compute the standardized censoring times $t_{c}std$. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Refer to the information for Example \ref{example:light.bulb.sample.size}.  Use (\ref{equation:m.for.unrest}) to compute the suggested $n$ for additional values of $\cihalfwidth_{T}=20,10,5$. Describe the effect that changing the target precision has on the needed sample size. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Refer to Example~\ref{example:insulation.plan.weibull.quantile}.  Use the given inputs and interpolation in Appendix Table~\ref{atable:lognormal.plan} to compute the needed sample size assuming that the distribution is lognormal instead of Weibull. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Refer to Example~\ref{example:insulation.plan.weibull.hazard}.  Use the given inputs to compute the needed sample size assuming that the distribution is lognormal instead of Weibull. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 A reliability engineer wants to run a life test to estimate the .05 quantile of the fatigue life distribution of a metal component used in a switch. The engineer has to choose a sample size that will allow estimation to be precise enough so that the lower endpoint of a 95\% confidence interval for the quantile will be about one half of the ML estimate. It will be possible to test each specimen until about 100 thousand cycles, when it is expected that about 15\% of the specimens will have failed. It is expected that about 5\% will have failed after about 40 thousand cycles. 
 

a. Use the information above on Weibull probability paper to obtain "planning values" for the Weibull parameters. 

a. Determine the sample size needed to achieve the desired precision.  


# From the Text Exercise 10.`r ex = ex+1; ex`

 Consider the sample size problem in Example~\ref{example:insulation.plan.weibull.quantile}.  Solve the same problem assuming that there is need to estimate $t_{.02}$ with $R_{T}=2.$ 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Do the calculations for Example~\ref{example:insulation.plan.lognormal.shape}. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Verify equation (\ref{equation:lsvcv}). 


# From the Text Exercise 10.`r ex = ex+1; ex`

 In some cases (e.g., for the lognormal distribution), planning values will be specified in terms of the shape parameter $\sigma$ and a particular quantile, say $t_{p_{1}}$ for a specified $p_{1}$.  Given these values, derive an expression for $\mu$ and for $t_{p_{2}}$ for a given $p_{2}$. 


# From the Text Exercise 10.`r ex = ex+1; ex`

 Refer to Appendix Table~\ref{atable:lognormal.plan}.  What can you say about the effect that censoring has on the correlation between ML estimators $\hat{\mu}$ and $\hat{\sigma}$? 


