---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 12.`r ex = ex+1; ex`

 A sample of 20 aluminum specimens was tested until fatigue failure. A probability plot showed that the lognormal distribution provides an adequate description of the spread in the data.  The sample mean and standard deviation of the logarithms of cycles-to-failure were 5.13 and .161, respectively. 
 

a. \label{exer.part.ln.pred.a} Compute a 95\% confidence interval for the median  of the cycles to failure distribution. 

a. \label{exer.part.ln.pred.b} Compute a 95\% prediction interval for the number of cycles to failure for a future specimen tested in the same way. Compare this with the "naive" prediction interval computed as if the estimates are the parameters. 

a. Redo parts~\ref{exer.part.ln.pred.a} and \ref{exer.part.ln.pred.b} supposing, instead, that the sample size had been 100 units. Comment on the results. 

a. Explain why there is so much difference between  the confidence interval in part~\ref{exer.part.ln.pred.a} and the prediction interval in part~\ref{exer.part.ln.pred.b}.  


# From the Text Exercise 12.`r ex = ex+1; ex`

 Show that putting together a one-sided lower and a one-sided upper 100$(1-\alpha/2)$\% prediction bounds for a future observation results in a two-sided 100$(1 - \alpha)$\% prediction interval for that observation. 


# From the Text Exercise 12.`r ex = ex+1; ex`

 \label{exercise:pi.normal.sigma.known} Suppose that $t_{1}, \dots, t_{n}$ is a random sample from a $LOGNOR(\mu, \sigma)$ distribution.  Suppose that $\sigma$ is known and let $\hat{\mu}_{n}=\bar{\grealrv}=\sum_{i=1}^{n}\grealrv_{i}/n$ where, $y_{i}=\log(t_{i})$.  Consider the prediction of a new time to failure observation $T$.  In this case, $\left [\log(T) -\hat{\mu}_{n} \right ]/\sqrt{Var(T -\hat{\mu}_{n})} = \left [\log(T) -\hat{\mu}_{n}]/[\sigma \sqrt{1+1/n} \right ] \sim NOR(0,1)$, which suggests the prediction interval 
$$
 \pinterval(1-\alpha)= \left [0, \quad \exp \left (\hat{\mu}_{n}+\sigma \sqrt{\frac{n+1}{n}}\, \,  	\Phi^{-1}_{\nor}(1-\alpha) \right ) \right ]. 
$$ 
 

a. \label{exer.part:item.coverage.probability} Show that $\cp[\pinterval(1-\alpha)]=1-\alpha$ for any $n$. 

a. Show that  
$$
 \cp[\pinterval(1-\alpha) \mid \hat{\mu}_{n} ; \mu] = \Phi_{\nor} \left [ \frac{\hat{\mu}_{n}-\mu}{\sigma} + \sqrt{\frac{n+1}{n}}\,\, \Phi^{-1}_{\nor}(1-\alpha) 	 \right ]. 
$$ 

a. Show that $\lim_{n \to \infty}\cp[\pinterval(1-\alpha) \mid \hat{\mu}_{n} ; \mu]=1-\alpha$. 

a. Show that $\cp[\pinterval(1-\alpha)] =\E_{\hat{\mu}_{n}} \left \{ \cp[\pinterval(1-\alpha) \mid \hat{\mu}_{n} ; \mu] \right \}=1-\alpha$. Notice the complexity of this computation when compared with the computation on part~\ref{exer.part:item.coverage.probability}. 

a. Derive an expression for a two-sided $100(1-\alpha)\%$ prediction interval for $T$. 

a. A naive prediction interval is $\pinterval(1-\alpha)=[0, \exp(\hat{\mu}+ \Phi^{-1}_{\nor}(1-\alpha) \times \sigma)]$.  Show that $\cp[\pinterval(1-\alpha)]= \Phi_{\nor}[\sqrt{n/(n+1)} \, \, \Phi^{-1}_{\nor}(1-\alpha)].$ Draw a graph of this coverage probability for values of $n=2,4,10$ over values of $1-\alpha$ in the interval $[.9,\,\, 1]$.  Comment on the coverage probabilities and their behavior as a function of the sample size.  


