---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 9.`r ex = ex+1; ex`

 Explain the possible advantages and disadvantages of using the bootstrap sampling methods illustrated in Figures~\ref{figure:parboot1fig.ps} and \ref{figure:parboot2fig.ps} when the goal is to obtain a confidence interval for  the quantile of a Weibull distribution under the following conditions with $n$ small (say 10) and $n$ large (say 100): 
 

a. A complete sample of $n$ failure times. 

a. A Type~II sample consisting of $r=n/2$ failures out of $n$ units. 

a. A Type~I censored sample, starting with $n$ units and censored at a point in time close to the median of the distribution. 

a. A randomly censored sample, starting with $n$ units where units are censored at random points  in time such that about 50\% of the units will be observed to fail and the others will be censored.  


# From the Text Exercise 9.`r ex = ex+1; ex`

 Refer to Figure~\ref{figure:shockabsB.weib.boot.mleprobplot.ps}. Using the ideas of the percentile bootstrap discussed in Section~\ref{section:percentile.bootstrap}, determine, approximately, a 95\% confidence interval for $t_{.2}$ of the shock absorber failure-time distribution. 


# From the Text Exercise 9.`r ex = ex+1; ex`

 Refer to Figure~\ref{figure:shockabsB.weib.boot.mleprobplot.ps}. Using the ideas of the percentile bootstrap discussed in Section~\ref{section:percentile.bootstrap}, determine, approximately, a 95\% confidence interval for $F(10000)$ of the shock absorber failure-time distribution. 


