---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 4.`r ex = ex+1; ex`

 Show that for a continuous $F(t)$, $h(t) = 1/\theta, t > 0$ is a constant (i.e., not depending on $t$) if and only if $T \sim EXP(\theta)$. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 Derive expressions for the mean, variance, and quantile functions of the exponential distribution. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 Derive the expression for $\Phi_{SEV}^{-1}(p)$ based on the expression for  $\Phi_{SEV}(z)$ in Section~\ref{section:sev.distribution.definition}. 


# From the Text Exercise 4.`r ex = ex+1; ex`

  Show that if $Y$ has a SEV$(\mu, \sigma)$ distribution then $-Y$ has a LEV$(-\mu, \sigma)$ distribution. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 Consider the Weibull distributions with parameters $\eta=10$ years, and $\beta=$.5, 1, 2, and 4. 
  

a.  Compute (using a computer if available) and graph the Weibull hf for $t$ ranging between 0 and 10. 

a. Explain the practical interpretation of the hf at $t=1$ and $t=10$ years. 

a. Compute and plot the Weibull cdfs over the same range of $t$. For which shape parameter value is the probability of failing the largest at 1 year? At 10 years? Explain.	   


# From the Text Exercise 4.`r ex = ex+1; ex`

 Consider the Weibull $h(t)$.  Note that when $\beta=1$, $h{(t)}$ is constant and that when $\beta=2$, $h(t)$ increases linearly.  	 Show that if 
  

a.  $0< \beta < 1$, then $h(t)$ is decreasing in $t$.  	  

a.  $1< \beta < 2$, then $h(t)$ is concave increasing. 

a.  $\beta > 2$, then $h(t)$ is convex increasing.  	   


# From the Text Exercise 4.`r ex = ex+1; ex`

 Starting with equation (\ref{equation:weibull.cdf}), show that the distribution of $Y=\log(T)$ is $SEV[\log(\eta),1/\beta]$. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 Derive the expression for $\Phi_{LOGIS}^{-1}(p)$ based on the expressions for $\Phi_{LOGIS}(z)$ given in Section~\ref{section:logistic.distribution.definition}. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 Even though, theoretically, the SEV, LEV, LOGIS, and NOR distributions can take on negative values, the probability of nonpositive outcomes is  negligible for certain combinations of parameters. 
 

a. For the combinations of parameter values for the SEV distribution shown in Figure~\ref{figure:distplot.sev.ps}, compute $\Pr(Y \leq 0)$. 

a. For the SEV, LEV, LOGIS, and NOR distributions, derive a general expression relating $\mu$ and $\sigma$, and guaranteeing that $\Pr(Y \leq 0) \leq \epsilon $.  


# From the Text Exercise 4.`r ex = ex+1; ex`

 Show that if $T$ is $LOGNOR(\mu,\sigma)$ then       $1/T$ is $LOGNOR(-\mu, \sigma)$. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 The exponential distribution is said to possess a "memoryless" property.  This memoryless property implies that a used unit is just as reliable as one that is new---that there is no wear out. Probabilistically this memoryless property can be stated as $\Pr(T \leq \delta) = \Pr(T\leq t_{0}+ \delta|T>t_{0})$ for any $t_{0}>0$. Show that for a continuous random variable, this memoryless property holds if and only if $T \simEXP(\theta)$. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 \label{exercise:weibullcv} The coefficient of variation, $\gamma_{2},$ is a useful scale-free measure of relative variability for a random variable. 
 

a. Derive an expression for the coefficient of variation for the Weibull distribution. 

a. Compute $\gamma_{2}$ for all combinations of $\beta=.5, 1, 3, 5$ and $\eta=50, 100.$ Also, draw (or use the computer to draw) a graph of the Weibull pdfs for the same combinations of parameters. 

a. Explain the effect that changes in $\eta$ and $\beta$ have on the shape of the Weibull density and the effect that they have on $\gamma_{2}.$  


# From the Text Exercise 4.`r ex = ex+1; ex`

 The coefficient of skewness, $\gamma_{3},$ is a useful scale-free measure of skewness in the distribution of a random variable. Do Exercise~\ref{exercise:weibullcv} for the coefficient of skewness. 


# From the Text Exercise 4.`r ex = ex+1; ex`

 \label{exercise:weibull.sim} Generate $500$ pseudorandom observations from a "parent" lognormal distribution with $\mu=5$ and $\sigma=.8$. 
 

a. Compare the histogram of the observations with a plot of the parent lognormal density function. 

a. Compute the sample median of the $500$ observations and compare it with the median of the parent lognormal distribution. 

a. Compute the sample mean of the $500$ observations and compare it with the mean of the parent lognormal distribution. 

a. Compute the sample standard deviation of the $500$ observations and compare with the standard deviation of the parent lognormal distribution.  


# From the Text Exercise 4.`r ex = ex+1; ex`

 Repeat Exercise~\ref{exercise:weibull.sim} using a Weibull distribution with $\eta=100$ and $\beta=.5.$  Comment on how the results differ from those with the lognormal distribution. 


