---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 19.`r ex = ex+1; ex`

 Explain the importance of having physical understanding of the physics or chemistry of failure mechanisms when one is doing accelerated life testing. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 \label{exercise:devicec.analysis} The following table contains data from an accelerated life test on  Device-C, an integrated circuit. Failures were caused by a chemical reaction inside the circuit package. Reliability engineers tested 10 circuits at each temperature over a period of 3000 hours. The purpose of the experiment was to estimate the activation energy of the failure-causing reaction and to obtain an estimate of the integrated circuit life distribution at $80\degreesc$ junction temperature. \\[3ex] 
$$
\begin{array}{ccl} Junction & \# of Units \\ Temperature &  Tested & Recorded Failure Times in Thousands of Hours \\ 
\hline
 $80\degreesc$ &10& None by 3000 hours\\ $125\degreesc$&10& None by 3000 hours\\ $150\degreesc$&10  & 2.35, 2.56, 2.98\\ $175\degreesc$&10 & .80, 1.13, 1.21, 1.31,  	1.35, 1.35, 1.37, 1.42, 1.77, 1.96\\ $200\degreesc$&10 & .22, .25, .28, .33,  	.37, .38, .46, .46, .51, .61 \\ 
\hline
 \\[2ex] 
\end{array}
$$
 
 

a. \label{exer.part:device.c.lognormal} For each temperature with failures, plot the ordered failure time $t_{(i)}$ versus $(i-.5)/10$ on lognormal probability paper. 

a. Repeat part~\ref{exer.part:device.c.lognormal}, but use Weibull probability paper. 

a. Make a judgment as to whether the lognormal or the Weibull distribution is a more adequate distribution for these data. 

a. Using the lognormal probability plot, draw a set of parallel straight lines through the plotted points, one line for each temperature having failures. 

a. Use each line on the probability plot to obtain graphical estimates of the .5 quantiles at the corresponding temperatures.  

a. Use each line on the probability plot to obtain graphical estimates of the .01 quantiles at the corresponding temperatures. Describe the nature of the extrapolation in these estimates. 

a. \label{exer.part:device.c.arrhen.plot} Plot the estimates of the .5 quantile versus temperature on Arrhenius paper. Draw a straight line to estimate the relationship between life and temperature. Do the same with the graphical estimates of the .01 quantile. 

a. Graphically estimate the slope of the lines drawn in part~\ref{exer.part:device.c.arrhen.plot}, and use these to obtain a graphical estimate of the failure mode's activation energy. 

a. Use the lines drawn in part~\ref{exer.part:device.c.arrhen.plot} to obtain estimates of the .01 and .5 quantiles of the life distribution of Device-C at $80\degreesc$. Describe the nature of the extrapolation in these estimates. 

a. Predict the effect on the estimates of the Arrhenius relationship if the data at $80\degreesc$ and $125\degreesc$ were to be omitted from the analysis. Explain.  


# From the Text Exercise 19.`r ex = ex+1; ex`

 Provide a list of the different things that one can learn from plotting individual nonparametric estimates and parametric ML estimates on Weibull probability paper (such as Figure~\ref{figure:mylarpoly.lnor.groupi.ps}). 


# From the Text Exercise 19.`r ex = ex+1; ex`

 Suppose that failure time $T \sim \LOGNOR(\mu,\sigma)$ at a given level of temperature and that the Arrhenius model can be used to get a temperature/time acceleration factor as in (\ref{equation:arrhenius.af}). Then show that the logarithm of quantiles of the failure-time distribution will be a linear function of $1/(\Tempc{} +273.15)$. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 Suppose that failure time $T \sim \WEIB(\mu,\sigma)$ at a given level of voltage and that the inverse power relationship can be used to get a voltage/time acceleration factor as in (\ref{equation:voltage.acceleration}). Then show that the logarithm of quantiles of the failure-time distribution will be a linear function of $\log({\rm Voltage})$. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 An analyst has fitted the Arrhenius-lognormal model \begin{displaymath} \Pr[\rv\leq t;\Temp] = \Phi_{\nor}  \left[\frac{\log(t)-\mu}{\sigma} \right] \end{displaymath} where $\mu =\beta_{0}+ \beta_{1} x$, $\sigma$ is constant and $x=1/(\Tempk{})$.  Show how $\beta_{1}$ in this model is related to activation energy $\Ea$ in the Arrhenius relationship. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 An analyst has fitted the Arrhenius-lognormal model \begin{displaymath} \Pr[\rv \leq t;\Temp] = \Phi_{\nor}  \left[\frac{\log_{10}(t)-\mu}{\sigma} \right] \end{displaymath} where $\mu = \beta_{0}+ \beta_{1} x$, where $\sigma$ is constant and $x=11605/(\Tempk{})$.  This differs from the model presented in Example~\ref{example:devicea.arr.log.model} because base-10 logarithms have been used (something done quite commonly, and usefully, in engineering and other non-mathematical disciplines). Show how estimates of $\beta_{0}, \beta_{1}, \sigma,$ and $t_{p}$ in this model relate to estimates in the traditional base-$e$ lognormal distribution. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 Refer to Example~\ref{example:ci.fhat.comp}.  Write down expressions that could be used to compute a normal-approximation confidence interval for the $p$ quantile of the life distribution at a specified level of temperature. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 \label{exercise:crisk.alt} A particular type of IC has two different failure modes, both of which can be accelerated by increasing temperature.  The random failure-time of Mode 1 is $T_{{\rm M}_{1}}$ and the random failure time due to Mode 2 is $T_{{\rm M}_{2}}$. In a unit, suppose that the IC fails at $T=\min(T_{{\rm M}_{1}},T_{{\rm M}_{2}})$. Failure mode ${\rm M}_{1}$ has an activation energy of $\Ea=1.4$ electron volts and failure mode ${\rm M}_{2}$ has an activation energy of $\Ea=.7$.  The physical nature of the failure mechanisms suggests that $T_{{\rm M}_{1}}$ and $T_{{\rm M}_{2}}$ are independent. The engineers involved believe that both $T_{{\rm M}_{1}}$ and $T_{{\rm M}_{2}}$ have a lognormal distribution.  At the proposed highest test temperature of $120\degreesc$, with failure time measured in hours, assume that $\mu_{1}=6.9$, $\sigma_{1}=.6$, $\mu_{2}=9.0$, and $\sigma_{2}=.8$. 
 

a. Assuming an Arrhenius ALT model, plot the median of the failure-time distribution versus temperature for failure mode ${\rm M}_{1}$ and also for failure mode ${\rm M}_{2}$. Plot using temperatures between the use temperature of $40\degreesc$ and $120\degreesc$. 

a. Plot the .1 and .9 quantiles of the mode ${\rm M}_{1}$ failure-time distribution and of the mode ${\rm M}_{2}$ failure-time distribution, as a function of temperature. 

a. Use the plots to help describe potential dangers of using a temperature-accelerated life test on a component, ignoring failure mode differences, when the  different failure modes have vastly different activation energies.  


# From the Text Exercise 19.`r ex = ex+1; ex`

 For a particular kind of insulating material, life can be described by the inverse power model  \begin{displaymath} \Pr[\rv\leq t;\Volt] = \Phi_{\sev}\left[\frac{\log(t)-\mu}{\sigma} \right] \end{displaymath} where $\sigma$ is constant, $\mu = \beta_{0}+ \beta_{1} x$, and $x=\log(\Volt)$. 
 

a. Show that  $\log(t_{p})$, the logarithm of the Weibull quantile, is a linear function of $\log(\Volt)$. 

a. Suppose that $100p_{1}$\% would fail at voltage $\Volt_{1}$ and $100p_{2}$\% would fail at voltage $\Volt_{2}$ before time $\censortime$. Derive an expression for the proportion failing at $\Volt_{3}$. 

a. Derive expressions for the inverse power relationship parameters $\beta_{0}$ and $\beta_{1}$ as functions of $p_{1}$, $p_{2}$, and $\sigma$.  


# From the Text Exercise 19.`r ex = ex+1; ex`

 Example~\ref{example:devicea.model.lrt} showed how to use an omnibus likelihood ratio test to compare fitting individual lognormal distributions at each level of temperature and fitting the Arrhenius-lognormal ALT model.  This provides an overall test for model adequacy. 
 

a. Explain, precisely, the hypothesis or hypotheses being tested in Example~\ref{example:devicea.model.lrt}. 

a. Explain which constrained and unconstrained models you would fit in order to test the assumption of a common $\sigma$ at all levels of temperature. Do not assume anything about the temperature-life relationship. 

a. Explain possible likelihood ratio tests on whether $\sigma$ is constant, under the assumption that $\mu$ is linearly related to $11605/\Tempk{}$. 

a. Explain how to do a likelihood ratio test to check the assumption that $\mu$ is linearly related to $11605/\Tempk{}$ versus an alternative relationship with curvature, assuming that $\sigma$ does not depend on temperature.  


# From the Text Exercise 19.`r ex = ex+1; ex`

 Refer to Example~\ref{example:ci.fhat.comp} for the Device-A data. Compute a confidence interval for the lognormal distribution $F(10000)$ at 10$\degreesc$. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 \label{exercise:mylar.lognormal} The ALT data on the mylar-polyurethane insulating structure in Appendix Table~\ref{atable:mylar.alt.data} are complete data (no censored observations). Thus it is possible to fit a lognormal distribution to these data using the standard least-squares regression analysis procedure in a standard statistical package. Use these data, dropping the 361.4 kV/mm observations, to do the following. 
 

a. Use such a statistical package to compute the least squares estimates for the inverse power relationship lognormal model. 

a. Plot the regression estimates of median of the failure-time distribution on log-log axes. Also plot the sample median at each level of voltage. What conclusions can you draw from this? 

a. Compare the least squares estimates with estimates obtained by using ML estimation with the inverse power relationship lognormal model. What differences do you notice in the parameter estimates?  


# From the Text Exercise 19.`r ex = ex+1; ex`

 Refer to Exercise~\ref{exercise:mylar.lognormal}.  Use a maximum likelihood program to fit the inverse power relationship Weibull model to these data. Compare Weibull and lognormal estimates of the .1 quantile of failure at 50 kV/mm. What do you conclude about the importance of the distribution used for this estimate? 


# From the Text Exercise 19.`r ex = ex+1; ex`

 \label{exercise:mylar.lognormal.all} Redo the analyses in Exercise~\ref{exercise:mylar.lognormal} but include the 361.4 kV/mm observations. What do you conclude? 

 
# From the Text Exercise 19.`r ex = ex+1; ex`

 \label{exercise:sigma.ratio} For Example~\ref{example:new.tech.ic}, using the results in Table~\ref{table:icdevice2.lognor.indiv.mles}, compute a 95\% normal-approximation confidence interval for the ratio $\sigma_{250}/\sigma_{300}$. Base the interval on the large sample distribution of $Z_{\log(\hat{\sigma}_{250}/\hat{\sigma}_{300})}$. 


# From the Text Exercise 19.`r ex = ex+1; ex`

 In Example~\ref{example:new.tech.ic}, there is evidence that $\sigma$ differs from one level of temperature to the other. 
 

a. Suppose that $\sigma$ is really changing (as suggested by the point estimates) describe the effect that using a constant $\sigma$ model would have on estimates of the life distribution at $100 \degreesc$. You do not need to do any numerical  computations; answer using intuition or analytical arguments. 

a. With reference to the simple Arrhenius-lognormal failure-time model described in Sections~\ref{section:arrhenius.af} and \ref{section:nonlin.deg.acc} suggest possible physical reasons (i.e., deviations from the simple model) that might cause $\sigma$ to change as a function of temperature.  


