---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 1.`r ex = ex+1; ex`

 Discuss the assumptions that would be needed to take the heat exchanger data for calendar time in Figure~\ref{figure:heatex.year.datafig.ps} and convert them to operating-time data shown in Figure~\ref{figure:heatex.stime.datafig.ps} and then use these data for purposes of analysis and inference on the life distribution of heat exchanger tubes of the type in these exchangers. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 It has been argued both that quality is a part of reliability and that reliability is a part of quality. Discuss the relationship between these two disciplines. To help make your discussion concrete, use your knowledge of a particular product to help express your ideas. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 In the development and presentation of traditional statistical methods, description and inference are often presented in terms of means and variances (or standard deviations) of distributions. 
 

a. Use some of the examples in this chapter to explain why, in many applications, reliability or design engineers would be more interested in the time at which $1\%$ (or some smaller percentage) of a particular component will fail instead of the time at which $50\%$ would fail. 

a. Explain why means and variances of time to failure may not be of such high interest in reliability studies. 

a. Give at least one example of a product for which mean time to failure would be of interest. Explain why.  


# From the Text Exercise 1.`r ex = ex+1; ex`

 Consider the following situations. For each, discuss the reasons why the study might be considered to be either analytic or enumerative. For each example outline the assumptions needed so that the sample data will be useful for making inferences about the population or process of interest. 
 

a. Ten light bulbs were selected at random points in time from a production process. One of these bulbs was then selected at random and put aside for future use. The other nine bulbs were tested until failure. The data from the nine failures were to be used to construct a prediction interval for the last bulb. 

a. A company has entered into a contract to buy a large lot of light bulbs. The price will be determined as a function of the average failure time of a random sample of $100$ bulbs. 

a. Example~\ref{example:heat.exchanger.data} 

a. Example~\ref{example:spacecraft.battery}  


# From the Text Exercise 1.`r ex = ex+1; ex`

 \label{exercise:time.scale} An important part of quantifying product reliability is specification of an appropriate time scale (or time scales) on which life should be measured (e.g., hours of operation, cycles of operation, etc.). For each of the following products, suggest and give reasons for an appropriate scale (or scales) upon which one might measure life for the following products. Also, discuss possible environmental factors that might affect the lifetime of individual units. 
 

a. Painted surface of an automobile. 

a. Automobile lead-acid battery. 

a. Automobile windshield wipers. 

a. Automobile tires. 

a. Incandescent light bulb.  


# From the Text Exercise 1.`r ex = ex+1; ex`

 For each of the products listed in Exercise~\ref{exercise:time.scale}, explain your best understanding of the underlying failure mechanism. Also, describe possible ways in which an analyst could define failure. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 \label{exercise:repair.or.not} For each of the following, discuss whether field failures of the unit or product should be considered to be a failure of a repairable system, a failure of replaceable unit within a system, or both. Explain why. 
 

a. Automobile alternator. 

a. Video cassette recorder. 

a. Microwave oven. 

a. Home air conditioner. 

a. Hand-held calculator. 

a. Clothes dryer.  


# From the Text Exercise 1.`r ex = ex+1; ex`

 For each of the products listed in Exercise~\ref{exercise:repair.or.not}, describe the range of environments that the product might encounter in use and the effect that environment could have on the product's reliability. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 Consider the turbine wheel data in  Table~\ref{table:turbine.data}. 
 

a. Compute the proportion cracked at each level of exposure. 

a. How do you explain the fact that the proportion of cracked wheels decreases as age increased at 14, 30, and 42  hundred hours of exposure? 

a. Discuss the assumptions that one would have to make to answer the questions  raised by the objectives listed in  Example~\ref{example:turbine.wheel.data}.  


# From the Text Exercise 1.`r ex = ex+1; ex`

 Construct a histogram for the V7 tube data in Table~\ref{table:v7.transmitter.tube}. Discuss alternative methods of handling the last open-ended time interval. What information does this plot provide? 


# From the Text Exercise 1.`r ex = ex+1; ex`

 Figure~\ref{figure:fan.histogram.ps} shows both the number of failures and the number of censored observations in each of 6 time intervals. Explain why such a graphical display needs to be interpreted differently than a histogram of uncensored failure times like Figure~\ref{figure:lzbearing.histogram.ps}. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 A telephone electronic switching system contains a large number of nominally identical circuit packs.  When a circuit pack fails, only a small part of the system's functionality is lost. Failed packs are replaced, as soon as possible, with new circuit packs.  All of the circuit packs have serial numbers and detailed records are kept so that the failure times are known for all packs that fail and so that the running times are known for all of the packs that do not fail.  In practice, to assess circuit pack reliability, it would be common to treat the circuit packs in the system as a sample from a larger population of circuit packs and use the data to make inferences about the larger population. 
 

a. \label{exercise:cirpack.population.def} List three distinct different {\em precise}  definitions for the larger population or process that could be of interest to reliability engineers, design engineers, or financial managers. 

a. For each of the definitions in part~\ref{exercise:cirpack.population.def}, state the assumptions that must be satisfied to make the desired inferences about the circuit pack life distribution. Comment on the reasonableness of these assumptions and how departures from the assumptions could result in misleading conclusions. 

a. Assume that you have been given the above description of a switching system and have been asked to attend a meeting where a study is to be planned to monitor, continuously, the early-life reliability (defined as the first 1000 hours) of circuit packs.  The purpose of the study is to determine the effect of recent design and manufacturing process changes on circuit pack reliability.  Data will be obtained from three particular systems that are physically close to the design and manufacturing facilities of the circuit pack manufacturer. Before offering advice on the plan you will need further information. Prepare a list of questions that you would ask of design engineers, reliability engineers, and manufacturing engineers who will be attending the meeting.  


# From the Text Exercise 1.`r ex = ex+1; ex`

 Explain how graphical methods can be used to complement analytical methods of data analysis. 


# From the Text Exercise 1.`r ex = ex+1; ex`

 There was a considerable amount of censoring at low levels of humidity in the printed circuit accelerated life test data shown in Figure~\ref{figure:luvalle.scatter.ps}. Explain how such censoring  can obscure important information about the relationship between humidity and time to failure. 


