---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 6.`r ex = ex+1; ex`

 For the $LOGLOGIS(\mu, \sigma)$ distribution with cdf 	  
$$
 F(t)=\Phi_{LOGIS} \left [ \frac{\log(t)-\mu}{\sigma} \right ], \quad t > 0; \quad -\infty< \mu <\infty, \sigma > 0,  	  
$$ 	  
 	  

a. 	  Find the probability scales that will linearize all of the cdfs in the logistic family. 

a. Use the scales to generate a proper labeled graph, and display the $LOGLOGIS(1, 1)$ and the $LOGLOGIS(1, 2)$ cdfs. 

a.  What quantile of this distribution corresponds to the scale parameter $\exp(\mu)$?  


# From the Text Exercise 6.`r ex = ex+1; ex`

 Starting with an ordinary piece of graph paper with linear divisions, perform the following steps to create Weibull probability paper with time ranging between $10$ and $1000$ and probability ranging between $.001$ and $.999.$ Refer to Figure~\ref{figure:loglinear.weibull.ps}  for an example. Alternatively, program a spread-sheet or statistical  package to do the same thing with computer graphics. 
 

a. Find values of $\log[-\log(1-p)]$ for $p=.001$ and $p=.999.$ Use these to develop a linear axis on the right-hand side of the graph. 

a. For selected values of $p$ between .001 and .999 (e.g., .001, .01, .1, .3, .5, .7, .9, .99, .999) compute $\log[-\log(1-p)].$ Find this value on the right-hand side axis to determine the location of the $p$ label on the left-hand side axis. 

a. Find values of $\log(t)$ for $t=10$ and $t=1000.$ Use these to develop a linear axis for $\log(t)$ on the top of the page. 

a. For selected values of $t$ between 10 and 1000 (e.g., 10, 20, 50, 100, 200, 500, 1000), compute $\log(t)$ and use the location on the top axis to determine the corresponding locations for the time labels on the bottom axis.  


# From the Text Exercise 6.`r ex = ex+1; ex`

 Consider the scale  parameter $\eta$ for the Weibull distribution. 
 

a. Show that $\eta=\exp(\mu)$ for the Weibull distribution is approximately equal to the $.63$ quantile. 

a. Discuss the practical importance of estimating $\eta$ for a population of integrated circuits to be installed in new personal computers. 

a. Is it possible to get a good graphical estimate of $\eta$ from a probability plot based on a life test for which only 3.5\% of the integrated circuits failed by the end of the test? 

a. For what Weibull "parameters" (i.e., functions of $\eta$ and $\beta$) can one get a good graphical estimates from such data?  


# From the Text Exercise 6.`r ex = ex+1; ex`

 Use the following 10 simulated observations from a Weibull distribution with $\eta=1$ and $\beta=2$ (so that $\mu=0$ and $\sigma=.5$) to make a Weibull probability plot and use it to obtain graphical estimates of the parameters $\eta$ and $\beta$.  $t_{i}=$.74, 1.21, .22, .37, 1.28, .73, .99, .67, .71, .33. How do the estimates compare with the "true parameter values"? 


# From the Text Exercise 6.`r ex = ex+1; ex`

  \label{exercise:bbear.nonpar.probplot} Consider the ball bearing fatigue data given in Example~\ref{example:ball.bearing.data} and Table~\ref{table:lz.bbearing.data}.  %------------------------------------------------------------------- 
 

a. Compute a nonparametric estimate of $F(t)$, the proportion of units failing as function of time. Plot your estimate on paper with linear scales. 

a. \label{exer.part:lnormal.prob.plot} Make a lognormal probability plot of the data. This is accomplished by ordering the failure times  in increasing order, $t_{(1)} \le \ldots \le t_{(23)}$.  Then plot $t_{(i)}$ versus $(i-.5)/n$ on lognormal  probability paper. 

a. \label{exer.part:weibull.prob.plot} Do the same as in part~\ref{exer.part:lnormal.prob.plot} but on Weibull probability paper.  

a. Comment on the adequacy of the lognormal and Weibull models to describe these data.  


# From the Text Exercise 6.`r ex = ex+1; ex`

 Use the answers to Exercise~\ref{exercise:earth.orbit.cdf} to do the following: 
 

a. Make a Weibull probability plot displaying the device failure data. 

a. Use the plotted points to estimate the proportion of devices that will fail before 10,000 hours of operation. 

a. Comment on whether the Weibull distribution fits the data well. 

a. Use the slope and location of this line to estimate the Weibull distribution parameters. 

a. Use the plotted points to estimate the proportion of devices that will fail before 100,000 hours. Comment on the usefulness of this estimate.  


# From the Text Exercise 6.`r ex = ex+1; ex`

  \label{exercise:fatigue.experiment} A sample of 100 specimens of a titanium alloy were subjected to a fatigue test to determine time to crack initiation. The test was run up to a limit of 100,000 cycles.  The observed times of crack initiation (in units of 1,000 of cycles) were: $18, 32, 39, 53, 59, 68, 77, 78, 93$. No crack had initiated in any of the other 91 specimens. 
 

a. Compute a nonparametric estimate, $\hat{F}(t)$, of the cdf $F(t)$ using both the simple binomial method and the Kaplan Meier method (in this case these two methods provide the same answer). 

a. Plot $\hat{F}(t)$ on linear axes. 

a. Use $\hat{F}(t)$ to compute plotting positions and plot the data on Weibull paper. Use the plot to obtain an estimate of the Weibull shape parameter~$\beta$. 

a. Comment on the adequacy of the Weibull distribution. 

a. Comment on the adequacy of the available data if the purpose of the  experiment was to estimate $t_{.1}$.  


# From the Text Exercise 6.`r ex = ex+1; ex`

 For the high-cycle fatigue life data in Exercise~\ref{exercise:parida.1991}, construct probability plots for the exponential, lognormal, Weibull, and gamma distributions (trying several values of $\gammashape$ for the gamma distribution). Which distributions appear suitable for describing the shape of the distribution in the lower tail? 


# From the Text Exercise 6.`r ex = ex+1; ex`

 Using the life test data on silicon photodiode detectors  from Exercise~\ref{exercise:weis.et.al.1986}, construct probability plots for the exponential, Weibull, and lognormal distributions. Which distributions look like they might provide an adequate model for photodiode detector life? 


# From the Text Exercise 6.`r ex = ex+1; ex`

 Figures~\ref{figure:loglinear.lognormal.ps} and  \ref{figure:loglinear.weibull.ps} have horizontal lines at the  standardized quantile value of 0. 
 

a. For Figure~\ref{figure:loglinear.lognormal.ps},  explain why the dotted line crosses the $F(t)$ scale at $F(t)=.5$. 

a. For Figure~\ref{figure:loglinear.weibull.ps}, compute the value of $F(t)$  where the dotted line crossed the 0 on the standardized quantile scale.  


# From the Text Exercise 6.`r ex = ex+1; ex`

 \label{example:graphical.T7987} Using the linear scales on the top and right of  Figure~\ref{figure:alloy.t7987.npp.lnor.ps}, we can use a straight line drawn through the data points to obtain graphical estimates of the lognormal distribution fit to the Alloy T7987 data. Use these estimates to compute a parametric estimate of F(200) by substituting them into (\ref{equation:lognormal.cdf}). 


# From the Text Exercise 6.`r ex = ex+1; ex`

 \label{example:graphical.T7987.a} Use Figures~\ref{figure:alloy.t7987.cdf.sim.ps},  \ref{figure:alloy.t7987.npp.weib.ps}, and  \ref{figure:alloy.t7987.npp.lnor.ps} to obtain nonparametric graphical estimates of $F(200)$ for the Alloy T7987 data. Are the answers similar? Explain why or why not. Compare your answers with those obtained in Exercise~\ref{example:graphical.T7987}. Explain the reason for observed differences. 


# From the Text Exercise 6.`r ex = ex+1; ex`

 Use the linear scales on the top and right of  Figure~\ref{figure:shockabsB.npp.weib.ps} to compute graphical estimates of the Weibull distribution parameters for the shock absorber data. 


