---
output: html_document
---

```{r echo=FALSE}
ex <- 0
```


# From the Text Exercise 8.`r ex = ex+1; ex`

 Use the ball bearing data from Exercise~\ref{exercise:bbear.nonpar.probplot} to do the following. 
 

a. \label{exer.part:parametric.lognormal} Fit a lognormal distribution to the data. To facilitate the computations, use the following  summary of the  data, 
$$
 \sum_{i=1}^{23} y_{i}=95.46, \quad \sum_{i=1}^{23} \left (y_{i} -\bar{y} 	        \right )^{2}=6.26 
$$ where $y_{i}=\log(t_{i})$ and $\bar{y}=\sum_{i=1}^{23} y_{i}/23$. Plot the fitted lognormal distribution along with the nonparametric estimate on lognormal probability plot paper like that used in Exercise~\ref{exercise:bbear.nonpar.probplot}\ref{exer.part:lnormal.prob.plot}. 

a. A computer program gives the following ML estimates for  a Weibull distribution, $\hat{\mu}=4.41$, $\hat{\sigma}=0.476$.  Do the same as in  \ref{exer.part:parametric.lognormal} but for the Weibull distribution. 

a. Comment on the adequacy of the lognormal and Weibull distributions to fit these data.   


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:heatex.comp} Use the heat exchanger tube crack data in Figure~\ref{figure:heatex.stime.datafig.ps} to do the following:      
 

a. Fit an exponential distribution to the data. (Note that this could be done  by fitting a Weibull distribution with $\beta$ constrained to be 1.) 

a. Fit a Weibull distribution to the  data. 

a. Compare the values of the log likelihood from the two different distributions. How do they compare and what does this suggest?  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Refer to Exercise~\ref{exercise:heatex.comp} and use the fitted Weibull and exponential distributions to do a likelihood ratio test to see if the data are consistent with a Weibull shape parameter $\beta=1$.  What is the implication of this hypothesis and what is your conclusion? 


# From the Text Exercise 8.`r ex = ex+1; ex`

 Refer to Exercise~\ref{exercise:heatex.comp} and use the Weibull distribution to:      
 

a. Compute an approximate 95\% confidence interval  for $F(2)$, the proportion of cracked tubes after 2 years of service, based on $Z_{\hat{F}(2)} \overset{\cdot}{\sim} NOR(0,1)$. 

a. Compute an approximate 95\% confidence interval  for $F(2)$,  based on $Z_{logit[\hat{F}(2)]} \overset{\cdot}{\sim} NOR(0,1)$. 

a. Explain why you might prefer to report one of these intervals over the other.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Return to the fatigue crack-initiation test in Exercise~\ref{exercise:fatigue.experiment}. Fit a Weibull distribution with a given shape parameter $\beta=2$.  
 

a.  Compute the ML estimate of $\eta$. What is the {\em practical} interpretation of this estimate? 

a. Obtain the estimate $\widehat{se}_{\hat{\eta}}$. 

a. Compute a conservative 95\% confidence interval for $\eta$. 

a. Plot the Weibull estimate of $F(t)$ along with the nonparametric estimate. Comment on the adequacy of the Weibull distribution to  describe the data. 

a. What is an estimate of the $.1$ quantile of the time-to-initiation distribution? 

a. Compute a conservative 95\% confidence interval for the $.1$ quantile of the time-to-initiation distribution.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Suppose that $\hat{g}$ is the ML estimate of a quantity $g$, and that  $\widehat{se}_{\hat{g}}$ is an estimated standard error. Show that a confidence interval for $g$, based on  $Z_{\log(\hat{g})}=[\log(\hat{g}) - \log(g)]/\widehat{se}_{\log(\hat{g})} \overset{\cdot}{\sim} NOR(0,1)$ has the form $ [ \underset{\sim}{g}, \quad \overset{\sim}{g}]= [\hat{g}/w, \quad  \hat{g} \times w] $ where $w=\exp[z_{(1-\alpha/2)} \widehat{se}_{\hat{g}}  /\hat{g}]$. 


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:ic.sing.alt} A particular type of integrated circuit (IC) is known to have an electromigration-related failure mode. A life test was conducted at a temperature of $120^{\circ}C$ in order to learn more about the life distribution and when failures might be expected to occur. A total of 20 ICs were tested and 5 failed before 500 hours, when the test was stopped. Failure times were at 252, 315, 369, 403, and 474 hours. ML estimates of the lognormal parameters are $\hat{\mu}=6.56$ and $\hat{\sigma}=.534$. The variance-covariance matrix estimate for $\hat{\mu}$ and $\hat{\sigma}$ is 
$$
 \widehat{\sum}_{\hat{\mu},\hat{\sigma}}= \left[  \begin{array}{rr} .0581 &.0374\\ .0374 & .0405 \end{array} \right]. 
$$ Recall that $\exp(\hat{\mu})=\exp(6.56)=706$ hours  is the ML estimate of the lognormal median. 
 

a. \label{exer.part:ic.sing.lnpp} Make a lognormal probability plot of the failure data. 

a. Compute ML estimates of the lognormal $F(200)$ and $F(1000)$ and use these to draw a line representing the lognormal estimate of $F(t)$. 

a. Use $\hat{\mu}$ and $\hat{\sigma}$ to compute an estimate of the mean of the lognormal distribution (equation given in Section~\ref{section:lognormal.distribution.def}).  Compare this with the estimate of the lognormal median. Comment on the difference. 

a. Compute $that_{.1}$, the ML estimate of  the .1 quantile of the life distribution. 

a. Compute the standard error for $that_{.1}$. Explain the interpretation of this quantity. 

a. Compute an approximate 95\% confidence interval for $t_{.1}$.   Include this interval in the plot in part~\ref{exer.part:ic.sing.lnpp}. Explain the interpretation of this interval and the justification for the approximate method that you use.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:weib.bulb} A life test was run on 20 prototype high-power RF transmitting tubes. In order to obtain tube life information more quickly, the tubes were tested at higher than usual levels of voltage.  The tubes were tested simultaneously until failure or until 1.50 thousand hours. Failures were observed at .82, .99, 1.06, 1.08, 1.24, 1.39, 1.40 thousand hours.  The other 13 tubes ran until 1.5 thousand hours without failure.  Based on experience with life tests on similar products, the engineers believe that the Weibull shape parameter is $\beta=3$. Do the following with $\beta$ fixed at at this value. 
 

a. \label{exer.part:hprf.probplot} Make a Weibull probability plot of these data. Determine if the data are consistent with the specified value of $\beta$. 

a. Compute the ML estimate of the Weibull scale parameter $\eta$. Compute and graph the ML estimate of $F(t)$ on the probability plot constructed in part~\ref{exer.part:hprf.probplot}. 

a. Compute a 95\% confidence interval for $\eta$. What is the practical interpretation of this interval? 

a. \label{exer.pt:weib.bulb} Compute the ML estimate and a 95\% confidence interval for $F(t)$ at $1000$ hours. 

a. Explain the interpretation of the confidence interval from part~\ref{exer.pt:weib.bulb}.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Redo Exercise~\ref{exercise:weib.bulb}, but use  $\beta=2$. Comment on the differences in the results and the potential effect of using an incorrect value of $\beta=3$, if the actual Weibull shape parameter is $\beta=2$. 


# From the Text Exercise 8.`r ex = ex+1; ex`

 Refer to Exercise~\ref{exercise:elec.sys}. Suppose now that failure analysis and previous experience suggests that Component-A life can be modeled adequately with a Weibull failure-time distribution. 
 

a. Compute and plot the ML estimate of $F(t)$ with a Weibull  distribution using given $\beta=3$. 

a. Compute and plot the ML estimate of $F(t)$ with a Weibull distribution using given $\beta=.33$. 

a. Compute and plot the Weibull $\hat{F}(t)$ and pointwise $95\%$ confidence intervals, estimating $\beta$ from the data. 

a. Compare the plots constructed above. Use these plots and describe the consequences of using a seriously incorrect value of $\beta$.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Use the diesel locomotive fan failure data in Appendix Table~\ref{atable:fan.data} to do the following: 
 

a.  Fit an exponential distribution to the fan data.   

a. Fit a Weibull distribution to the fan data.   

a.  Do a likelihood ratio test that the Weibull shape parameter is equal to 1. How would the conclusion affect fan replacement policy?   

a.  Compute an approximate 95\% confidence interval for $t_{.1}$, the time at which 10\% of the fan population will fail, based on $Z_{that_{.1}} \overset{\cdot}{\sim} NOR(0,1)$.   

a.  Compute an approximate 95\% confidence interval for $t_{.1}$, based on $Z_{\log(that_{.1})} \overset{\cdot}{\sim} NOR(0,1)$.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 Nelson~(1982, page 529) analyzes failure data to compare two different snubber designs (a snubber is a component in a toaster).  The data are in Appendix Table~\ref{atable:snubber.data}. 
 

a.   Use probability plots and maximum likelihood fits  to assess the adequacy of different parametric distributions for the data from the old design. 

a.   Analyze the new-design data in the same way to assess if there is evidence that the distributions differ. Section~\ref{section:product.comparison} describes analytical methods for such comparisons.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:weibull.likelihood} Consider a sample of $n$ observations with  $t_{1}$, \ldots, $t_{r}$ reported as exact failure times (suppose that $2 \leq r \leq n$) and $n-r$ observations censored at a common time  $t_{c}$. Provide a simple expression for the Weibull log likelihood  in the $\eta=\exp(\mu)$ and $\beta=1/\sigma$ parameterization. 


# From the Text Exercise 8.`r ex = ex+1; ex`

 Write the Weibull likelihood for a sample  containing both exact failure times and right censored values, using $\sigma$ and $t_{p}$ as the distribution parameters (for some specified fixed $0<p<1$). Explain how to use this likelihood to compute a profile likelihood for $t_{p}$. 


# From the Text Exercise 8.`r ex = ex+1; ex`

 As explained in Section~\ref{section:known.sigma.inference}, data analysis with the Weibull distribution is simpler and estimates are more precise if the Weibull shape parameter is given. 
 

a. Explain the dangers of using a specified Weibull shape parameter value when analyzing life data. 

a. A reliability engineer for a project claims that the Weibull shape parameter is known for a population of components. How would you, as an analyst, approach the problem of working with the engineer to make a reliability prediction based on a limited censored sample?  


# From the Text Exercise 8.`r ex = ex+1; ex`

 A random sample of five new automobile horns was taken from early production.  The horns were tested simultaneously in a simulated use environment (with heat, humidity, salt air, and vibration) until each horn had reached a total of six hundred thousand cycles. There were no failures in the test.  The reliability specification for the horns says that $t_{.01}$ for the horn's life distribution should be at least two hundred thousand cycles.  The dominant failure mode for similar horns, manufactured in the past, was stress-corrosion induced fatigue cracking and this failure mode had a Weibull shape parameter of $\beta=1/\sigma=2.3$. 
 

a. Using the given value of $\beta$, compute a lower 95\% confidence bound for $t_{.01}$ of the horn's life distribution. 

a. Do the results contradict reliability specification?  Do the results demonstrate the reliability specification? What is the difference? 

a. Suggest, based on physical considerations, arguments to convince someone that it is possible that the test might lack validity for testing the reliability specification.  


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:zero.failures.weibull} Analysis of field data has suggested that a particular engine bearing is an important life limiting component.  The responsible engineers believe that improving the bearing's reliability would have an important effect on overall engine reliability.  A redesigned bearing was tested extensively in a bench life test with simulated loads. Ten bearings were tested, each for 500 hours, with no reported failures. On the basis of previous field failure data for this class of bearing, a Weibull distribution with a shape parameter of $\beta=2.3$ had provided an adequate  description for the life of this bearing. Find a 95\% lower confidence bound for the .01 quantile of the bearing life distribution. 


# From the Text Exercise 8.`r ex = ex+1; ex`

 \label{exercise:zero.failures.lognormal} Consider the problem described in Exercise~\ref{exercise:zero.failures.weibull} but suppose that the presumed distribution was lognormal with $\sigma=.55$. 
 

a. \label{exer.part:zero.failures.lognormal1} Use the nonparametric method in Chapter 3 to obtain an approximate 95\% upper confidence bound for $F(500)$. 

a.  \label{exer.part:zero.failures.lognormal2} Use the nonparametric upper confidence bound from part~\ref{exer.part:zero.failures.lognormal1}  and the lognormal distribution assumption to obtain a 95\% lower confidence bound for the .01 quantile of the bearing life distribution. 

a. Explain the relationship between the interval given in part~\ref{exer.part:zero.failures.lognormal2} and the corresponding method for the Weibull distribution explained in Section~\ref{section:weib.zero.fail}.  


