---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

Welcome to the course!  

1. Install the R project for statistical computing.  The current version is `r R.version.string` to the computers you intend to work on.

    + For AFIT computers, go to the network folder R:/Stats/R. Double-click the install link for the latest version available and follow the prompts for a standard installation.

    + For home computers, R can be installed directly from <http://www.r-project.org/>.  Click on the CRAN link on the left side and install the current version for your OS.

2. Install the RStudio IDE

    + For AFIT computers, see network folder R:/Stats/R. Double-click the "RStudio.exe" file for the latest version available and follow the prompts for a standard installation.

    + For home computers, install directly from <http://www.rstudio.com/products/rstudio/download/>.  Click on the installer link at the bottom of the page for the appropriate operating system.

3. Install the RSPLIDA package, the R version of the software package put out by Meeker & Escobar.  

    + On the Blackboard page for this course, access the "R & RSplida" folder and download the RSplidaAlpha.zip file to your computer.  Make sure to note the location where this file was saved.

4. Read Appendix B and Chapter 1 in Meeker & Escobar.  We'll cover these pretty quickly the first week.
