---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__A telephone electronic switching system contains a large number of nominally identical circuit packs.  When a circuit pack fails, only a small part of the system's functionality is lost. Failed packs are replaced, as soon as possible, with new circuit packs.  All of the circuit packs have serial numbers and detailed records are kept so that the failure times are known for all packs that fail and so that the running times are known for all of the packs that do not fail.  In practice, to assess circuit pack reliability, it would be common to treat the circuit packs in the system as a sample from a larger population of circuit packs and use the data to make inferences about the larger population.__
 
a. __List three distinct different $\mathit{precise}$  definitions for the larger population or process that could be of interest to reliability engineers, design engineers, or financial managers.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __For each of the definitions in part (a), state the assumptions that must be satisfied to make the desired inferences about the circuit pack life distribution. Comment on the reasonableness of these assumptions and how departures from the assumptions could result in misleading conclusions.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Assume that you have been given the above description of a switching system and have been asked to attend a meeting where a study is to be planned to monitor, continuously, the early-life reliability (defined as the first 1000 hours) of circuit packs.  The purpose of the study is to determine the effect of recent design and manufacturing process changes on circuit pack reliability.  Data will be obtained from three particular systems that are physically close to the design and manufacturing facilities of the circuit pack manufacturer. Before offering advice on the plan you will need further information. Prepare a list of questions that you would ask of design engineers, reliability engineers, and manufacturing engineers who will be attending the meeting.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
