---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Consider the following situations. For each, discuss the reasons why the study might be considered to be either analytic or enumerative. For each example outline the assumptions needed so that the sample data will be useful for making inferences about the population or process of interest.__

a. __Ten light bulbs were selected at random points in time from a production process. One of these bulbs was then selected at random and put aside for future use. The other nine bulbs were tested until failure. The data from the nine failures were to be used to construct a prediction interval for the last bulb.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __A company has entered into a contract to buy a large lot of light bulbs. The price will be determined as a function of the average failure time of a random sample of $100$ bulbs.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Example 1.5.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Example 1.9.__  

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
