---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__For each of the products listed in Exercise 1.5 explain your best understanding of the underlying failure mechanism.  Also, describe possible ways in which an analyst could define failure.__

a. __Painted surface of an automobile__ 

`r SMRD.resources:::solution()$begin` 
Today's automobile coatings are complicated systems consisting of a base primer coat, paints with color, and a clearcoat top layer. These coating systems degrade chemically, especially when exposed to UV (ultraviolet) radiation. The degradation is accelerated with higher temperatures, humidity, and cycling of these variables.  UV degradation can be retarded by putting UV absorbers in the coating mixtures. Defects in application, such as thin spots, can cause especially early failures.  In controlled testing, the amount of UV exposure would be the most accurate time scale.  When gathering customer data, age of the automobile, part of the country where it is typically driven, and parking habits of the owner/user might provide reasonable surrogate information.  Failure in this case might be defined by the diameter of a chip in the paint or the number of paint chips over a defined surface area.  Finally, failure may be defined as the point when the gloss on the finish reaches a certain level of dullness.
`r SMRD.resources:::solution()$end`
    
b. __Automobile lead-acid battery__ 

`r SMRD.resources:::solution()$begin` 
Standard automobile lead-acid batteries for automobiles powered by internal-combustion engines are designed to serve as float batteries and also have a large amount of power to start the engine. Most of the power to actually run the automobile comes from the alternator. Although lead-acid batteries will degrade over time even if not discharged, these batteries suffer especially heavy degradation when they endure deep discharge-charge cycles. Cold weather is more stressful for such batteries because less charge can be held in lower temperatures, more power is needed to turn an engine that is cold, and engines are harder to start when it is cold.  Batteries that are designed to provide the main source of power for vehicles (lead-acid and other types) are designed to withstand larger numbers of charge/discharge cycles, but would have less power available for starting a large engine. Charge-discharge cycles are still the appropriate time scale.  Again, in controlled testing, the number of charge-discharge cycles would be an appropriate scale in which to measure degradation and life of a rechargeable battery.  Failure of a battery is typically defined as the time at which the voltage in the weakest cell falls below a certain threshold.
`r SMRD.resources:::solution()$end`

c. __Automobile windshield wipers__ 

`r SMRD.resources:::solution()$begin`
The rubber in automobile windshield wipers degrades over time as result of exposure to an external environment. This degradation can be accelerated by UV exposure. The proper time scale in this case would be the number of use-cycles (passes across the windshield), By establishing a baseline environment (lab environment, for example) UV exposure cn be included as an accelerating factor depending on the amount of use relative to real time and the amount of UV exposure. A common practice with such products is to "age" them at high levels of temperature and UV and then to test life or durability of the aged units.
`r SMRD.resources:::solution()$end`

d. __Automobile tires__ 

`r SMRD.resources:::solution()$begin`
For the most part, tires wear as a function of the number of miles driven.  The wear rate may be affected by temperature, driving style, age of the tire, over or under inflation, etc. Tires also degrade chemically over time, especially when exposed to UV.  Failure of a tire is usually defined as the point at which the tred has worn to a specified level.  Tires become more brittle, due to ageing chemical degradation. In the process, they sometimes develop cracks, especially in the sidewall. Of course tires can also fail from puncture or other accidents.
`r SMRD.resources:::solution()$end`

e. __Incandescent light bulb__ 

`r SMRD.resources:::solution()$begin`
The filaments in an operating incandescent light bulb will evaporate over time. When a bulb is turned on and off, thermal gradients cause mechanical shocks that can lead to fatigue. It is usually such a shock that causes a light bulb to fail (you may have noticed that light bulbs are more likely to fail when you first turn them on). Vibration can also accelerate fatigue failure.  Failure is usually simple to define in this case: the filament burns out and bulb stops functioning.
`r SMRD.resources:::solution()$end`
