---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__For each of the products listed in Exercise 1.7, describe the range of environments that the product might encounter in use and the effect that environment could have on the product's reliability__

a. __Automobile alternator__ 

`r SMRD.resources:::solution()$begin`
Elevated temperatures during operation, low temperatures at start up during the Winter months, signigicant vibration loads from engine operation and impact with potholes, speedbumps, etc., hundreds of thermal cycles between 0$^o F$ at start up and 200$^o F$ during operation, exposure to corrosive environments from spilled/leaking engine fluids as well as spray from road moisture combined with snow melt chemicals.
`r SMRD.resources:::solution()$end`

b. __Video cassette recorder__ 

`r SMRD.resources:::solution()$begin`
Drops during shipment, high use patterns, electrical surges, plugging into receptacle with improper home wiring, improper usage (inserting foreign objects)
`r SMRD.resources:::solution()$end`

c. __Microwave oven__

`r SMRD.resources:::solution()$begin`
Drops during shipment, high use patterns, electrical surges, plugging into receptacle with improper home wiring, improper use (putting things in that don't belong
`r SMRD.resources:::solution()$end`

d. __Home air conditioner__

`r SMRD.resources:::solution()$begin`
High usage during Summer months, dormant failures from cold exposure during Winter, impact from objects (toys, balls, tree limbs)
`r SMRD.resources:::solution()$end`

e. __Hand-held calculator__

`r SMRD.resources:::solution()$begin`
Impacts from dropping on floor or into a bookbag, high usage
`r SMRD.resources:::solution()$end`

f. __Clothes dryer__

`r SMRD.resources:::solution()$begin`
High usage, improper maintenace (not cleaning lint trap), excessive usage (routinely putting larger loads than designed), improper usage (inserting foreign objects) 
`r SMRD.resources:::solution()$end`
