---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Refer to Appendix Table C.20.  What can you say about the effect that censoring has on the correlation between ML estimators $\widehat{\mu}$ and $\widehat{\sigma}$?__

`r SMRD.resources:::solution()$begin`
The correlation between $\mu$ and $\sigma$ is calculated as

$$
\frac{f_{12}}{\sqrt{f_{11}}\sqrt{f_{22}}}
$$ 

With no censoring we can see from the Table C.20 that $\widehat{\mu}$ and $\widehat{\sigma}$ are independent. As the number of censored observations increases the correlation between $\widehat{\mu}$ and $\widehat{\sigma}$ becomes stronger.  The intuition for this result is that with a very small percentage of units failing, the extrapolated estimate of $\exp[\mu]=t_{0.5}$ is highly dependent.

Using values from Table C.20 we can plot the correlation against the values of $\zeta_c$. As seen in the graph below, $\mu$ and $\sigma$ are strongly correlated when $\zeta_c$ is between -3 and 0, and thus when $t_c$ is far below the population mean failure time.  When $t_c$ exceeds the population mean failure time, i.e. $\zeta_c \in (0,3)$, $\mu$ and $\sigma$ become uncorrelated.

```{r,echo=FALSE, fig.align='center'}
par(lwd = 2, font = 2, cex = 1.2)
zeta_c <- seq(-3,3,0.2)
rho <- table.lines(zeta_c,'normal')$rho
plot(x = zeta_c,
     y = rho,
     ylab = expression(Correlation~(rho)), 
     xlab = expression(zeta[c]),
     las = 1, 
     type = 'o',
     pch = 16, col = 'blue')
```
`r SMRD.resources:::solution()$end`
