---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__If we plan a life test to run until $5\%$ of 100 units will fail and if we are interested in estimating $t_{0.1}$, the time at which $10\%$ of the population of such units will fail, we will be extrapolating when we make the inference. Consider that the same life test might also be used to to estimate $t_{0.001}$, the time at which $0.1\%$ of the population will have failed.__

a. __Explain (and perhaps draw a picture to help with the explanation) why this is also extrapolation.__

`r SMRD.resources:::solution()$begin`
Statistical models are used to estimate functional relationships between input variables and output variables.  These models are based on empirical data observed during one or more experiments.  Often experiments will investigate the functional relationships over a small range of input variables.  For example, an experiment might investigate how automobile paint degrades over time when subjected to multiple levels of UV radiation.  Suppose that the experiment only considered UV levels in the range $[a,b], a<b$.  

Extrapolation would result if this  the model was used to predict the amount of degradation that would occur at UV levels below $a$ or above $b$.  This is extrapolation because it assumes that the relationship between degradation and UV radiation would not change at higher leves that what was investigated.  While this assumption may be correct, we have no way to evidence to support it.

For the scenario described in this exercise, only $5\%$ of the units being tested actually failed.  With this data we could build a model to estimate $t_{0.01},\ldots, t_{0.05}$.  However, using this model to estimate $t_{0.1}$ assumes that the observed failure process would remain unchanged if the test had continued until $10\%$ of the units had failed. Further, note that the width of any confidence intervals produced using this model will only account for sampling error but will not account for possible model error (the actual cdf may not be a straight line on the lognormal plot).  

This same argument holds if we were interested in estimating $t_{0.001}$, with the exception that we would be extrapolating to the left. 
`r SMRD.resources:::solution()$end`

b. __What has to be done to design a life test to estimate $t_{0.001}$ that will not involve extrapolation?__

`r SMRD.resources:::solution()$begin`
Taking a much larger sample size would allow estimation without extrapolation (and would also reduce sampling error). To estimate the time at which $1/1000$ will fail, it would make sense to test at least 1000 units and wait until at least one or two fail.
`r SMRD.resources:::solution()$end`
