---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Consider the sample size problem in Example 10.7.  Solve the same problem assuming that there is need to estimate $t_{.02}$ with $R_{T}=2$__

`r SMRD.resources:::solution()$begin`
If failure times are assumed to follow a log-location scale distribution, the following expression can be used to determine the required number of samples to estimate a quantile value with precision factor $R_{T}$

$$
n = \frac{z^2_{(1-\alpha/2)}V^{\Box}_{\log(\widehat{t}_{p})}}{[\log(R_{T})]^{2}}.
$$

From Example 10.7, we know that $\alpha=0.05$, thus $z^2_{(1-0.05/2)} = 1.96^2= `r qnorm(0.975)^2`$. The instructions from this exercise dicate that a precision factor of $R_{T} = 2$ should be used, implying that $[\log(2)]^2=`r log(2)^2`$.  Therefore, the only unknown term in the above expression is the unscaled quantile variance factor $V^{\Box}_{\log(\widehat{t}_{p})$.  The scaled quantile variance factor can be taken directly from Figure 10.5 (entering with $p_{c}^{\Box}=0.2$ and $p = 0.02$).  From the figure we obtain $\frac{1}{\sigma^2}V^{\Box}_{\log(\widehat{t}_{p})} \approx 30$.  A more accurate value may be obtained using the `variance.factor` function as shown below.

```{r, echo=TRUE}
SMRD::variance.factor(distribution = 'sev',
                      type = 'quantile',
                      quantile.of.interest = 0.02,
                      proportion.failing = 0.2)
```

From Example 10.1 we see that $\sigma_{\Box}=1.244$ which can be used to compute the value of the unscaled variance factor as $V^{\Box}_{\log(\widehat{t}_{p})} = 31.07 \times 1.244^{2} = 48.08$. Substututing these values into the above expression gives

$$
\frac{z^{2}_{(1-\alpha/2)}V^{\Box}_{\log(\widehat{t}_{0.02})}}{[\log(R_{T})]^{2}} = \frac{(1.96)^{2}(48.08)}{[\log(2)]^{2}} \approx 385 \mbox{ samples}.
$$
`r SMRD.resources:::solution()$end`
