---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Suppose that $t_{1}, \dots, t_{n}$ is a random sample from a $LOGNOR(\mu, \sigma)$ distribution.  Suppose that $\sigma$ is known and let $\hat{\mu}_{n}=\bar{y}=\sum_{i=1}^{n}y_{i}/n$ where, $y_{i}=\log(t_{i})$.  Consider the prediction of a new time to failure observation $T$.  In this case, $\left [\log(T) -\hat{\mu}_{n} \right ]/\sqrt{Var(T -\hat{\mu}_{n})} = \left [\log(T) -\hat{\mu}_{n}]/[\sigma \sqrt{1+1/n} \right ] \sim NOR(0,1)$, which suggests the prediction interval__

$$
PI(1-\alpha)= \left [0, \quad \exp \left (\hat{\mu}_{n}+\sigma \sqrt{\frac{n+1}{n}}\, \,  	\Phi^{-1}_{_{NOR}}(1-\alpha) \right ) \right ]. 
$$ 
 
a. __Show that $CP[PI(1-\alpha)]=1-\alpha$ for any $n$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

b. __Show that__

$$
CP[PI(1-\alpha) \mid \hat{\mu}_{n} ; \mu] = \Phi_{_{NOR}} \left [
\frac{\hat{\mu}_{n}-\mu}{\sigma} + \sqrt{\frac{n+1}{n}}\,\,
\Phi^{-1}_{_{NOR}}(1-\alpha)\right ]. 
$$ 

c. __Show that $\lim_{n \to \infty}CP[PI(1-\alpha) \mid \hat{\mu}_{n} ; \mu]=1-\alpha$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

d. __Show that $CP[PI(1-\alpha)] =E_{\hat{\mu}_{n}} \left \{CP[PI(1-\alpha) \mid \hat{\mu}_{n} ; \mu] \right \}=1-\alpha$. Note the complexity of this computation when compared with the computation in part (a).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

e. __Derive an expression for a two-sided $100(1-\alpha)\%$ prediction interval for $T$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

f. __A naive prediction interval is $PI(1-\alpha)=[0, \exp(\hat{\mu}+ \Phi^{-1}_{_{NOR}}(1-\alpha) \times \sigma)]$.  Show that $CP[PI(1-\alpha)]= \Phi_{_{NOR}}[\sqrt{n/(n+1)} \, \, \Phi^{-1}_{_{NOR}}(1-\alpha)].$ Draw a graph of this coverage probability for values of $n=2,4,10$ over values of $1-\alpha$ in the interval $[.9,\,\, 1]$.  Comment on the coverage probabilities and their behavior as a function of the sample size.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
