---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__A total of 100 new units have been introduced into service.  It is believed that the underlying time to failure distribution is Weibull. The analysts have available prior information and censored data on a sample of $n$ similar units.__

a. __Given a Monte Carlo sample of 2000 pairs of $\mu^{*},\sigma^{*}$ values from the posterior pdf $f(\mu,\sigma | \DATA)$, show how to compute marginal posterior predictive distribution for $T_{(1)}$, the time of the first failure out of the 100 units. Also show how to get a 95\% lower Bayesian prediction bound for $T_{(1)}$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Suppose that you can compute (but perhaps not write in closed form) the joint posterior pdf $f(\mu,\sigma |DATA)$. Explain how you could, using numerical integration and other numerical (but not simulation) methods, compute marginal posterior predictive pdf  and a $95\%$ lower Bayesian prediction bound for $T_{(1)}$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
