---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: true
---

__Consider the model used in Example 15.6, with the generalization that only a proportion $\xi$ of the units in the population are susceptible to failure mode S.__

a. __Write down expressions for the cdf and pdf of the overall failure-time distribution.__

`r SMRD.resources:::solution()$begin`
In Example 15.6 it was assumed that every unit under test was susceptible to the surge failure mode, thus $\xi = 1$.  The system cdf $F_{_{T}}(t)$ under this assumption can be expressed as

$$
\begin{aligned}
F_{_{T}}(t)&=1-[1-F_{_{S}}(t)][1-F_{_{W}}(t)]\\\\
&=1-(1-F_{_{W}}(t)-F_{_{S}}(t)+F_{_{S}}(t)F_{_{W}}(t))\\\\
&=F_{_{W}}(t)+F_{_{S}}(t)-F_{_{S}}(t)F_{_{W}}(t).
\end{aligned}
$$

Example 15.6 states that the failure times for each mode (assuming that only one failure mode was present) were modeled by distinct Weibull distributions.  Thus, substituting the respective Weibull cdfs into the system cdf expression above gives

$$
\begin{aligned}
F_{_{T}}(t)&=
1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right] +
1-\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right] -
\left(1-\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]\right)
\left(1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\right)\\\\
&=2-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right] -
\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right] -
\left(1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]-\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]+\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]\right)\\\\
&=1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right].
\end{aligned}\tag{1}
$$ 

The pdf for this system can be found by taking the derivative of the system cdf with respect to $t$.  Performing this derivative gives the following expression.

$$
\begin{aligned}
f_{_{T}}(t)&=\frac{\partial F_{_{T}}(t)}{\partial t}\\\\
&=\frac{\partial\left( 1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]\right)}{\partial t}\\\\
&= \frac{\beta_{_{W}}}{\eta_{_{W}}}\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_{_{W}}-1}\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\times\frac{\beta_{_{S}}}{\eta_{_{S}}}\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_{_{S}}-1}\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right].
\end{aligned}
$$

For this exercise, the cdf and pdf expressions shown above model the system failure probability for the $100 \times \xi\%$ of systems that are susceptible to surge failures.  For the $100 \times (1-\xi)\%$ of systems that are not susceptible to surge failures, the cdf is expressed as 

$$
\begin{aligned}
F_{_{T}}(t)&=1-[1-F_{_{W}}(t)]\\\\
&=F_{_{W}}(t))\\\\
&=1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right].
\end{aligned}\tag{2}
$$

and the pdf is expressed as

$$
\begin{aligned}
f_{_{T}}(t)&=\frac{\partial F_{_{T}}(t)}{\partial t}\\\\
&=\frac{\beta_{_{W}}}{\eta_{_{W}}}\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_{_{W}}-1}\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right].
\end{aligned}
$$

Thus, two mutually exclusive contributions to the system failure probability exist as shown in Equations (1) and (2).  The system cdf for the total population is found by summing the cdfs for both sub-populations, where each cdf is weighted by $\xi$, as shown below

$$
F_{_{T}}(t) = \xi\left(1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]\right) + (1-\xi)\left(1-\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\right).
$$

Similarly, the system pdf for the total population is found by taking the derivative of the system cdf for the total population shown above, which is expressed as

$$
\begin{aligned}
f_{_{T}}(t)=\;&\xi\left\{\frac{\beta_{_{W}}}{\eta_{_{W}}}\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_{_{W}}-1}\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\times\frac{\beta_{_{S}}}{\eta_{_{S}}}\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_{_{S}}-1}\exp\left[-\left(\frac{t}{\eta_{_{S}}}\right)^{\beta_S}\right]\right\}+\\\\
&(1-\xi)\left\{\frac{\beta_{_{W}}}{\eta_{_{W}}}\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_{_{W}}-1}\exp\left[-\left(\frac{t}{\eta_{_{W}}}\right)^{\beta_W}\right]\right\}.
\end{aligned}
$$
`r SMRD.resources:::solution()$end`

a. __Write a computer program to compute and plot the hazard function for this model.  Find combinations of the five parameters that give a bathtub-shaped hazard function.__

`r SMRD.resources:::solution()$begin`
Now, are tasked with finding combinations of the five parameters $\beta_{_{W}},\eta_{_{W}},\beta_{_{S}},\eta_{_{S}},\xi $ that produce a hazard function with a bathtub-shaped plot.  Recall, the hazard function, $h(t)$, is expressed as $h(t) = \frac{f(t)}{1-F(t)}$.  For this exercise, the system hazard function can be expressed (quite simply) with the R function defined in the chunk below. 

```{r}
system_haz <- function(x, beta1, eta1, beta2, eta2, xi) {
  
  cdf1 <- pweibull(q = x, shape = beta1, scale = eta1)
  cdf2 <- pweibull(q = x, shape = beta2, scale = eta2)
  pdf1 <- dweibull(x = x, shape = beta1, scale = eta1)
  pdf2 <- dweibull(x = x, shape = beta2, scale = eta2)
  system_cdf <- xi * (cdf1 + cdf2 - cdf1 * cdf2) + (1 - xi) * cdf2
  system_pdf <- xi * (pdf1 * pdf2) + (1 - xi) * pdf2
  
  return(system_pdf / (1 - system_cdf))
}
```

Using this function we can test various parameter combinations

`r SMRD.resources:::solution()$end`
