---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__A company that runs a fleet of passenger automobiles would like to do a retrospective study to compare two different brands of automobile batteries.  The fleet contains 55 automobiles. All  of the automobiles started with brand B, but during the life of the automobiles, when a battery failed, it was replaced with either Brand A or Brand B. The available data show the date of purchase of the original automobile and the date and brand of replacement for batteries that were replaced.__

a. __How would you organize the data for analysis? What kind of questions could you answer from an analysis focusing on the mean cumulative number of failures?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Describe some of the potential pitfalls involved in drawing inferences from a retrospective study like this. What advantages would there be for doing a prospective study where the failure times of future batteries would be studied?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __What assumptions would you have to make about the battery failures in order to be able to use the times between battery failures to estimate such a failure-time distribution for the batteries?  How could you use the available data to check the assumptions?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
