---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Return to the capacitor life test data in Example 17.11.  Physical theory suggests that the Weibull shape parameter $\beta=1/\sigma$ will depend on temperature if there is unit-to-unit variability in both the initial level of dielectric degradation and in dielectric degradation rate. Insulation engineers were interested in using these data to see if there was evidence for a temperature or voltage effect on $\beta=1/\sigma$.__
 
a. __Use the fitted model in Table 17.3 giving the Weibull distribution estimates at each combination of the individual experimental conditions. Compute the sum of the log likelihoods for all of the conditions.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Plot, on Weibull probability paper, the estimates of the Weibull cdfs for each test condition, as done in Figure 17.11.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Fit an indicator-variable regression model to the capacitor life test data such that there is a constant value of $\sigma$ but that a separate value of $\mu$ is estimated at each test condition.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compare the sum of the likelihoods from part (a) with the likelihood obtained from the model in part (c). Use these results to test if there is evidence for nonconstant $\sigma$ in these data. What do you conclude?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
