---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Equation (18.6) gives the Arrhenius relationship between the location parameter of the log-life distribution and temperature. When needed,  suppose that $\beta_{0}=-17$, $\beta_{1}=.86$, and $\sigma=1.2$. Using this model:__

a. __Give an expression for $\t_{p}$, the $p$ quantile  as a function of temperature in $^{\circ}C$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Show that the relationship between $\log(\t_{p})$ versus $1/K$ is linear.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Starting with linear graph paper, make an "Arrhenius plot" for this model, similar to Figure 18.5.  Start by plotting the linear relationship in part (b) on linear paper over the range of interest. Use a range of temperature running from $50^{\circ}C$ to $140^{\circ}C$.  Note that in order to have the slope of the plotted line decreasing in with temperature, it will be necessary to have the $1/K$ axis running left to right from largest to smallest values of $1/K$ (instead of the customary increasing axis). Then, finally, add in new (nonlinear) axes for Time and $^{\circ}C$.  Generally it is most convenient to do this on the axis opposite to the corresponding linear axis. On these axes, use tick and tick labels at major points on the scale (e.g., for temperature at $50, 60, \dots , 140$, corresponding to $1/K=.003094538, 0.003001651,\dots , 0.002420428$).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
