---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

___A particular type of IC has two different failure modes, both of which can be accelerated by increasing temperature.  The random failure-time of Mode 1 is $T_{{\rm M}_{1}}$ and the random failure time due to Mode 2 is $T_{{\rm M}_{2}}$. In a unit, suppose that the IC fails at $T=\min(T_{{\rm M}_{1}},T_{{\rm M}_{2}})$. Failure mode ${\rm M}_{1}$ has an activation energy of $E_{a}=1.4$ electron volts and failure mode ${\rm M}_{2}$ has an activation energy of $E_{a}=.7$.  The physical nature of the failure mechanisms suggests that $T_{{\rm M}_{1}}$ and $T_{{\rm M}_{2}}$ are independent. The engineers involved believe that both $T_{{\rm M}_{1}}$ and $T_{{\rm M}_{2}}$ have a lognormal distribution.  At the proposed highest test temperature of $120^{o}C$, with failure time measured in hours, assume that $\mu_{1}=6.9$, $\sigma_{1}=.6$, $\mu_{2}=9.0$, and $\sigma_{2}=.8$.__

a. __Assuming an Arrhenius ALT model, plot the median of the failure-time distribution versus temperature for failure mode ${\rm M}_{1}$ and also for failure mode ${\rm M}_{2}$. Plot using temperatures between the use temperature of $40^{o}C$ and $120^{o}C$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Plot the .1 and .9 quantiles of the mode ${\rm M}_{1}$ failure-time distribution and of the mode ${\rm M}_{2}$ failure-time distribution, as a function of temperature.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the plots to help describe potential dangers of using a temperature-accelerated life test on a component, ignoring failure mode differences, when the  different failure modes have vastly different activation energies.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
