---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__If a continuous random variable $T$ has a cdf $F(t)=Pr(T\le t)$, then it is easy to show that the transformed random variable $F(T)$ follows a $UNIF(0,1)$ distribution.  A similar property for random variables is that the cumulative hazard transformation $H(T)$ follows an exponential distribution.  Show this.__

`r SMRD.resources:::solution()$begin`
The first sentence in this problem states that given a random variable $T$ with continuous distribution function $F_{_T}(t)$, the transformed random variable $U=F_{_T}(T)\sim U(0,1)$. It should be understood that we can apply many functions to transform a random variable.  In this case the function we are applying is the cdf itself.  This special type of transformation is known as the Probability Integral Transform (PIT).  We will discuss the PIT later in this course as a way to simulate values from candidate distributions to fit to a data set.  The proof for this statement is as follows

Define the random variable $U\sim U(0,1)$ having cdf $F_{_U}(u)=P(U\le u)=u$.  If we apply the transformation $U=F_{_T}(T)$ where $T$ is any continuous random variable then

$$
\begin{aligned}
P(U\le u)&=P(F_{_T}(t)\le u)\\
&=P(T\le F_{_T}^{-1}(u))\\
&=F_{_T}(F_{_T}^{-1}(u))\\
&=u \hspace{60pt} q.e.d.\\
\end{aligned}
$$

Now, we have established that $F_{_T}(T) \sim U(0,1)$, therefore we define $U=F_{_T}(T)$.  We want to find the distribution of $V=H_{_T}(T)$.  We can accomplish this using either the cdf or the pdf of $V$, let's start with the cdf:

Because of the relationship between the cdf and the cumulative hazard we know $U=1-\exp\left\{ -V \right\}$.  Therefore $V=-\log \left(1-U \right), 0<V<\infty$.  The cdf of $V$ may then be expressed as 

$$
\begin{aligned}
P(V\le v)&=P(-\log \left(1-U \right)\le v)\\
&=P(1-U > \exp(-v))\\
&=P(U\le 1-\exp(-v))\\
&=F_{_U}(1-\exp(-v)\\
&=1-\exp(-V)
\end{aligned}
$$

Which is the cdf of the $\text{Exp}(1)$ distribution

For the pdf case, we note that the Jacobian $J$ of the transformation is  
\[J = \left| \frac{d}{dV}U \right| = \exp\left\{ -V \right\}\] 
>and $f_{_V}(v) = f_{_U}(1-\exp(-v))J = \exp\left\{ -V \right\}$ for $0<V<\infty$ which is the pdf of the $\text{Exp}  (1)$ distribution.
`r SMRD.resources:::solution()$end`
