---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Consider a random variable with cdf $F(t)=t/2$, $0 < t \leq 2$. Do the following:__

a. __Derive expressions for the corresponding pdf and hazard functions.__ 

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the results of part (a) to verify the relationship given in (2.2).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Sketch (or use the computer to draw) the cdf and pdf functions.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Sketch (or use the computer to draw) the hazard function. Give a clear intuitive reason for the behavior of $h(t)$ as $t \rightarrow 2$. Hint: by the time $t=2$, all units in the population must have failed.__ 

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Derive an expression for $t_{p}$, the $p$ quantile of $F(t)$, and use this expression to compute $t_{.4}$. Illustrate this on your plots of the cdf and pdf functions.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute $\Pr(.1 < T \leq .2)$ and $\Pr(.8 < T \leq .9)$. Illustrate or indicate this  probabilities on your graphs.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute $\Pr(.1 < T \leq .2 \mid T>.1)$ and $\Pr(.8 < T \leq .9 \mid T > .8)$.  Compare your answers with the approximation in (2.1).__  

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Explain the results in  in part (g) and give a general result on the relationship  between  $\Pr(t< T< t \mid T>t)$  and the approximation in (2.1).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
