---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__In planning an ALT, the large-sample approximate variance of the ML estimator of a particular quantile of the failure-time distribution at use conditions is often used to judge the precision that one could expect from a proposed test plan. Suppose that the Arrhenius/lognormal model will provide an adequate description of the relationship between life and temperature. As described in Appendix Section B.6.2, there are computer algorithms that can be used to compute the large-sample approximate  covariance matrix $\boldsymbol{\Sigma}_{\widehat{\theta}}$ of the ML estimates $\hat{\beta}_{0}$, $\hat{\beta}_{1}$, and $\hat{\sigma}$. In this case, $\boldsymbol{\Sigma}_{\widehat{\theta}}$ will be a function of the proposed test plan and the parameters $\beta_{0}$, $\beta_{1}$, and $\sigma$.__

a. __Given the individual elements of $\boldsymbol{\Sigma}_{\widehat{\theta}}$, provide an expression for the large-sample approximate variance of the ML estimator of the $p$ quantile at use temperature $\mathtt{Temp_{U}}$. Do not use matrix algebra.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Approximate standard errors of ML estimators from a proposed test plan can also be obtained by using Monte Carlo simulation. Explain the advantages and disadvantages of this approach relative to using the large-sample approximate variance.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
