---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__An ALT is going to be conducted to investigate the effect of size on the life of an insulating material. The accelerating variable will be voltage. Based on previous experience, for purposes of planning the experiment, use the model__

$$
Pr[T \leq t;\mathtt{thick,vpm}] = \Phi_{_{sev}}  \left[\frac{\log(t)-\mu(\mathtt{thick,vpm}])}{\sigma} \right]
$$

__where $\mu = \beta_{0}+ \beta_{1} \mathtt{thick} + \beta_{2} \mathtt{vpm}$, $\mathtt{thick}$ is the specimen size in cm, $\mathtt{vpm}$ is voltage stress in volts per mm, and $\sigma$ is constant.__

a. __What would be the model relating $\mu$ to the $\mathtt{thick}$ and voltage (instead of volts/mm)?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __What is an important advantage of modeling and experimenting in terms of $\mathtt{vpm}$ and $\mathtt{thick}$ rather than voltage and $\mathtt{thick}$?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
