---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Use the ball bearing life test data in Table 1.1 to do the following:__

a. __Compute a nonparametric estimate of the population fraction failing by $75$ million cycles.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the conservative interval in (3.2) to compute an approximate $90\%$ confidence interval for the population fraction failing by $75$ million cycles.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the normal-approximation method in (3.3) to compute an approximate $90\%$ confidence interval for the population fraction failing by $75$ million cycles.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Comparing the intervals from parts (a) and (b), what do you conclude about the adequacy of the normal-approximation method for these data?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
