---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Weis, Caldararu, Snyder, and Croitoru (1986) report on the results of a life test on silicon photodiode detectors in which 28 detectors were tested at $85^\circ C$ and 40 volts reverse bias. These conditions, which were more stressful than normal use conditions, were used in order to get failures quickly. Specified electrical tests were made at 0, 10, 25, 75, 100, 500, 750, 1000, 1500, 2000, 2500, 3000, 3600, 3700, and 3800 hours to determine if the detectors were still performing properly. Failures were found after the inspections at 2500 (1 failure), 3000 (1 failure), 3500 (2 failures), 3600 (1 failure), 3700 (1 failure), and 3800 (1 failure). The other 21 detectors had not failed after 3800 hours of operation. Use these data to estimate the life distribution of  such photodiode detectors running at the test conditions.__ 
 
a. __From the description given above, the data would be useful for making inferences about what particular populations or process? Explain your reasoning.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute and plot a nonparametric estimate of the cdf for time to failure at the test conditions.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute standard errors for the nonparametric estimate in part (b).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute a set of pointwise approximate $95\%$ confidence intervals for $F(t)$ and add these to your plot.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute simultaneous approximate $95\%$ confidence bands for $F(t)$ over the complete range of observation.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Provide a careful explanation of the differences in interpretation and application of the pointwise confidence intervals and the simultaneous confidence bands.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
