---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Example 3.9 illustrates the computations for the nonparametric estimation of the cdf for the shock absorber data up to 12,220~km. Complete the computations for the rest of the data (i.e., out to 28,100~km). Use $S(12200)=.9086984$ to continue the cumulative product in (3.6).__

a. __Plot the nonparametric estimate out to 28,100 km.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute $\widehat{se}_{\hat{F}}$ out to 28,100 km.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute a set of pointwise approximate $90\%$ confidence intervals for $F(t)$ out to 28,100 km and add these to the plot in part (a).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Explain why, with right-censored data, for the nonparametric estimation method, there is only a limited range of time over which we can estimate $F(t)$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
