---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Use the data in Table 1.4 to do the following for the V7 Transmitter tube:__

a. __Compute an estimate of the conditional probability of failing for each cell.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute a nonparametric estimate for $F(t)$ for each cell.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Plot the estimate of $F(t)$ along with a set of pointwise approximate 95\% confidence intervals.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __For each interval, compute and plot an estimate of the probability of failing in that interval given a unit enters the interval.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Explain how these estimates could be used to plan for preventive maintenance for a group of radio transmitters, each with one such tube.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
