---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Parida (1991) gives data from a load-controlled high-cycle fatigue test conducted on 130 chain links. The 130 links were randomly selected from a population of different heats used to manufacture the links. Each link was tested until failure or until it had run for 80 thousand cycles, whichever came first. There were 10 failures---one each reported at 33, 46, 50, 59, 62, 71, 74, and 75 thousand cycles and 2 reported at 78 thousand cycles. The other 120 links had not failed by 80 thousand cycles.__
 
a. __Use (3.1) to compute the nonparametric estimate of $F(t)$ and corresponding standard errors.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute a set of pointwise approximate $90\%$ confidence intervals for $F(t)$.  Explain the proper interpretation of these intervals.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __For the first 3 failures, compare the numerical estimates from (3.7) with the numerical estimates from (3.1).__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __The original paper reported the number of cycles to failure, as given above. Suggest reasons why the numbers of cycles to failures were not given with more precision and the effect that this has on the results of the analysis.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __The original paper reported that the tested units had been selected from a random sample of heats. What might have happened in the experiment if all of the sample links had been selected from just one or two heats?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __The original paper did not report the order in which the tests were run. Typically fatigue tests require the use of  one or a few expensive test stands and tests are done in sequence. The order in which the failures occurred was not described in the original paper. Is it possible that there was some useful information in knowing the order in which the 130 units had been tested? Discuss.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
