---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: no
---

__Generate $500$ pseudorandom observations from a "parent" lognormal distribution with $\mu=5$ and $\sigma=.8$.__

a. __Compare the histogram of the observations with a plot of the parent lognormal density function.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute the sample median of the $500$ observations and compare it with the median of the parent lognormal distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute the sample mean of the $500$ observations and compare it with the mean of the parent lognormal distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute the sample standard deviation of the $500$ observations and compare with the standard deviation of the parent lognormal distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
