---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Consider the scale parameter $\eta$ for the Weibull distribution.__

a. __Show that $\eta=\exp(\mu)$ for the Weibull distribution is approximately equal to the $.63$ quantile.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Discuss the practical importance of estimating $\eta$ for a population of integrated circuits to be installed in new personal computers.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Is it possible to get a good graphical estimate of $\eta$ from a probability plot based on a life test for which only $3.5\%$ of the integrated circuits failed by the end of the test?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __For what Weibull "parameters" (i.e., functions of $\eta$ and $\beta$) can one get a good graphical estimates from such data?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
