---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Use the answers to Exercise 3.6 to do the following:__

a. __Make a Weibull probability plot displaying the device failure data.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the plotted points to estimate the proportion of devices that will fail before 10,000 hours of operation.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Comment on whether the Weibull distribution fits the data well.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the slope and location of this line to estimate the Weibull distribution parameters.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Use the plotted points to estimate the proportion of devices that will fail before 100,000 hours. Comment on the usefulness of this estimate.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
