---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Consider the case of $n$ observations reported as "exact" failure times from an $EXP(\theta)$ distribution.__

a. __Show that the ML estimate, $\hat{\theta}$, of $\theta$ is the sample mean, say $\bar{t}=\sum_{i=1}^{n}t_{i}/n$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Show that the relative likelihood has the simple expression__
$$
 R(\theta)=\exp(n) \left (\frac{\bar{t}}{\theta}\, \right )^{n} \exp \left ( - \frac{n\bar{t}}{\theta} \,\right ). 
$$  

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Explain how to use $R(\theta)$ to obtain an approximate confidence interval for $\theta$ based on inverting a likelihood ratio test [i.e., assume that when evaluated at the true value of $\theta$, $R(\theta) \overset{\cdot}{\sim} \mathcal{X}^{2}_{1}$].__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Suppose that $n=4$ and $\bar{t}=0.87$. Obtain  the ML estimate and an approximate $90\%$ confidence interval for $\theta$ using the method in part (c). Plot $R(\theta)$ to facilitate your work.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
