---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Use the ball bearing data from Exercise 1.1 to do the following.__

a. __Fit a lognormal distribution to the data. To facilitate the computations, use the following summary of the data,__
$$
\sum_{i=1}^{23} y_{i}=95.46, \quad 
\sum_{i=1}^{23} \left (y_{i} -\bar{y}\right )^{2}=6.26 
$$ 
__where $y_{i}=\log(t_{i})$ and $\bar{y}=\sum_{i=1}^{23} y_{i}/23$. Plot the fitted lognormal distribution along with the nonparametric estimate on lognormal probability plot paper like that used in Exercise 6.5b.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __A computer program gives the following ML estimates for  a Weibull distribution, $\hat{\mu}=4.41$, $\hat{\sigma}=0.476$.  Do the same as in (a) but for the Weibull distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Comment on the adequacy of the lognormal and Weibull distributions to fit these data.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
