---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Refer to Exercise 7.4. Suppose now that failure analysis and previous experience suggests that Component-A life can be modeled adequately with a Weibull failure-time distribution.__
 
a. __Compute and plot the ML estimate of $F(t)$ with a Weibull  distribution using given $\beta=3$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute and plot the ML estimate of $F(t)$ with a Weibull distribution using given $\beta=.33$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compute and plot the Weibull $\hat{F}(t)$ and pointwise $95\%$ confidence intervals, estimating $\beta$ from the data.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Compare the plots constructed above. Use these plots and describe the consequences of using a seriously incorrect value of $\beta$.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
