---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__A random sample of five new automobile horns was taken from early production.  The horns were tested simultaneously in a simulated use environment (with heat, humidity, salt air, and vibration) until each horn had reached a total of six hundred thousand cycles. There were no failures in the test.  The reliability specification for the horns says that $t_{.01}$ for the horn's life distribution should be at least two hundred thousand cycles.  The dominant failure mode for similar horns, manufactured in the past, was stress-corrosion induced fatigue cracking and this failure mode had a Weibull shape parameter of $\beta=1/\sigma=2.3$.__

a. __Using the given value of $\beta$, compute a lower $95\%$ confidence bound for $t_{.01}$ of the horn's life distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Do the results contradict reliability specification?  Do the results demonstrate the reliability specification? What is the difference?__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __Suggest, based on physical considerations, arguments to convince someone that it is possible that the test might lack validity for testing the reliability specification.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
