---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Analysis of field data has suggested that a particular engine bearing is an important life-limiting component.  The resonsible engineers believe that improving the bearing's reliability would have an important effect on overall engine reliability.  A redesigned bearing was tested extensively in a bench life-test with simulated loads.  Ten bearings were tested, each for 500 hours, with no reported failures.  On the basis of previous field failure data for this class of bearing, a Weibull distribution with a shape parameter of $\beta=2.3$ had provided an adequate description for the life of this bearing.  Find a 95% lower confidence bound for the $.01$ quantile of the bearing life distribution.__

`r SMRD.resources:::solution()$begin`
Using a fixed value for $\beta=2.3$, an approximate $95\%$ lower confidence bound on $\eta$ is

$$
\underline{\eta}=\left(\frac{2\sum_{i=1}^{n}[t_{i}]^{2.3}}{\chi^{2}_{(0.95,2)}}\right)^{1/2.3}=\left(\frac{2\times10\times[500]^{2.3}}{5.99}\right)^{1/2.3}=\left(\frac{2\times 2692801}{5.99}\right)^{1/2.3}=844.457\text{ hours}.
$$

From this, an approximate $95\%$ lower confidence bound on $t_{0.01}$ is expressed as

$$
\underline{t_{_{0.01}}}=\underline{\eta}\times(-\text{log}[1-0.01])^{1/2.3}=114.28 \text{ hours}.
$$
`r SMRD.resources:::solution()$end`
