---
output:
  html_document:
params:
  setup: '`r SMRD.resources:::setup( )`'
  show_solution: false
---

__Explain the possible advantages and disadvantages of using the bootstrap sampling methods illustrated in Figures 9.1 and 9.2 when the goal is to obtain a confidence interval for  the quantile of a Weibull distribution under the following conditions with $n$ small (say 10) and $n$ large (say 100):__

a. __A complete sample of $n$ failure times.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __A Type II sample consisting of $r=n/2$ failures out of $n$ units.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __A Type I censored sample, starting with $n$ units and censored at a point in time close to the median of the distribution.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`

a. __A randomly censored sample, starting with $n$ units where units are censored at random points  in time such that about $50\%$ of the units will be observed to fail and the others will be censored.__

`r SMRD.resources:::solution()$begin`
`r SMRD.resources:::solution()$end`
